#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TASK.DATA
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="ConnectALS")]
	public partial class ConnectAlsContextDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertEXP_AWB(EXP_AWB instance);
    partial void UpdateEXP_AWB(EXP_AWB instance);
    partial void DeleteEXP_AWB(EXP_AWB instance);
    #endregion
		
		public ConnectAlsContextDataContext() : 
				base(global::TASK.DATA.Properties.Settings.Default.ConnectALSConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public ConnectAlsContextDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ConnectAlsContextDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ConnectAlsContextDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ConnectAlsContextDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<EXP_AWB> EXP_AWBs
		{
			get
			{
				return this.GetTable<EXP_AWB>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.EXP_AWB")]
	public partial class EXP_AWB : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private decimal _AWBID;
		
		private string _WAREHOUSE;
		
		private string _AWBNO;
		
		private System.Nullable<int> _BOOKED_PIECES;
		
		private string _RECEIVED_STATUS;
		
		private string _RECEIVED_DATETIME;
		
		private System.Nullable<int> _RECEIVED_PIECES;
		
		private string _DEPARTED_STATUS;
		
		private string _DEPARTED_DATETIME;
		
		private System.Nullable<int> _DEPARTED_PIECES;
		
		private System.Nullable<System.DateTime> _CREATED_AT;
		
		private System.Nullable<System.DateTime> _LAST_CHANGED_AT;
		
		private System.Nullable<System.DateTime> _UPDATED_AT;
		
		private System.Nullable<System.DateTime> _UPDATED_BOOKING;
		
		private string _SHC;
		
		private string _WEIGHT;
		
		private string _USER_ACTION;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnAWBIDChanging(decimal value);
    partial void OnAWBIDChanged();
    partial void OnWAREHOUSEChanging(string value);
    partial void OnWAREHOUSEChanged();
    partial void OnAWBNOChanging(string value);
    partial void OnAWBNOChanged();
    partial void OnBOOKED_PIECESChanging(System.Nullable<int> value);
    partial void OnBOOKED_PIECESChanged();
    partial void OnRECEIVED_STATUSChanging(string value);
    partial void OnRECEIVED_STATUSChanged();
    partial void OnRECEIVED_DATETIMEChanging(string value);
    partial void OnRECEIVED_DATETIMEChanged();
    partial void OnRECEIVED_PIECESChanging(System.Nullable<int> value);
    partial void OnRECEIVED_PIECESChanged();
    partial void OnDEPARTED_STATUSChanging(string value);
    partial void OnDEPARTED_STATUSChanged();
    partial void OnDEPARTED_DATETIMEChanging(string value);
    partial void OnDEPARTED_DATETIMEChanged();
    partial void OnDEPARTED_PIECESChanging(System.Nullable<int> value);
    partial void OnDEPARTED_PIECESChanged();
    partial void OnCREATED_ATChanging(System.Nullable<System.DateTime> value);
    partial void OnCREATED_ATChanged();
    partial void OnLAST_CHANGED_ATChanging(System.Nullable<System.DateTime> value);
    partial void OnLAST_CHANGED_ATChanged();
    partial void OnUPDATED_ATChanging(System.Nullable<System.DateTime> value);
    partial void OnUPDATED_ATChanged();
    partial void OnUPDATED_BOOKINGChanging(System.Nullable<System.DateTime> value);
    partial void OnUPDATED_BOOKINGChanged();
    partial void OnSHCChanging(string value);
    partial void OnSHCChanged();
    partial void OnWEIGHTChanging(string value);
    partial void OnWEIGHTChanged();
    partial void OnUSER_ACTIONChanging(string value);
    partial void OnUSER_ACTIONChanged();
    #endregion
		
		public EXP_AWB()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AWBID", DbType="Decimal(18,0) NOT NULL", IsPrimaryKey=true)]
		public decimal AWBID
		{
			get
			{
				return this._AWBID;
			}
			set
			{
				if ((this._AWBID != value))
				{
					this.OnAWBIDChanging(value);
					this.SendPropertyChanging();
					this._AWBID = value;
					this.SendPropertyChanged("AWBID");
					this.OnAWBIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WAREHOUSE", DbType="VarChar(4)")]
		public string WAREHOUSE
		{
			get
			{
				return this._WAREHOUSE;
			}
			set
			{
				if ((this._WAREHOUSE != value))
				{
					this.OnWAREHOUSEChanging(value);
					this.SendPropertyChanging();
					this._WAREHOUSE = value;
					this.SendPropertyChanged("WAREHOUSE");
					this.OnWAREHOUSEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AWBNO", DbType="VarChar(12)")]
		public string AWBNO
		{
			get
			{
				return this._AWBNO;
			}
			set
			{
				if ((this._AWBNO != value))
				{
					this.OnAWBNOChanging(value);
					this.SendPropertyChanging();
					this._AWBNO = value;
					this.SendPropertyChanged("AWBNO");
					this.OnAWBNOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BOOKED_PIECES", DbType="Int")]
		public System.Nullable<int> BOOKED_PIECES
		{
			get
			{
				return this._BOOKED_PIECES;
			}
			set
			{
				if ((this._BOOKED_PIECES != value))
				{
					this.OnBOOKED_PIECESChanging(value);
					this.SendPropertyChanging();
					this._BOOKED_PIECES = value;
					this.SendPropertyChanged("BOOKED_PIECES");
					this.OnBOOKED_PIECESChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RECEIVED_STATUS", DbType="VarChar(8)")]
		public string RECEIVED_STATUS
		{
			get
			{
				return this._RECEIVED_STATUS;
			}
			set
			{
				if ((this._RECEIVED_STATUS != value))
				{
					this.OnRECEIVED_STATUSChanging(value);
					this.SendPropertyChanging();
					this._RECEIVED_STATUS = value;
					this.SendPropertyChanged("RECEIVED_STATUS");
					this.OnRECEIVED_STATUSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RECEIVED_DATETIME", DbType="VarChar(500)")]
		public string RECEIVED_DATETIME
		{
			get
			{
				return this._RECEIVED_DATETIME;
			}
			set
			{
				if ((this._RECEIVED_DATETIME != value))
				{
					this.OnRECEIVED_DATETIMEChanging(value);
					this.SendPropertyChanging();
					this._RECEIVED_DATETIME = value;
					this.SendPropertyChanged("RECEIVED_DATETIME");
					this.OnRECEIVED_DATETIMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RECEIVED_PIECES", DbType="Int")]
		public System.Nullable<int> RECEIVED_PIECES
		{
			get
			{
				return this._RECEIVED_PIECES;
			}
			set
			{
				if ((this._RECEIVED_PIECES != value))
				{
					this.OnRECEIVED_PIECESChanging(value);
					this.SendPropertyChanging();
					this._RECEIVED_PIECES = value;
					this.SendPropertyChanged("RECEIVED_PIECES");
					this.OnRECEIVED_PIECESChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DEPARTED_STATUS", DbType="VarChar(8)")]
		public string DEPARTED_STATUS
		{
			get
			{
				return this._DEPARTED_STATUS;
			}
			set
			{
				if ((this._DEPARTED_STATUS != value))
				{
					this.OnDEPARTED_STATUSChanging(value);
					this.SendPropertyChanging();
					this._DEPARTED_STATUS = value;
					this.SendPropertyChanged("DEPARTED_STATUS");
					this.OnDEPARTED_STATUSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DEPARTED_DATETIME", DbType="VarChar(500)")]
		public string DEPARTED_DATETIME
		{
			get
			{
				return this._DEPARTED_DATETIME;
			}
			set
			{
				if ((this._DEPARTED_DATETIME != value))
				{
					this.OnDEPARTED_DATETIMEChanging(value);
					this.SendPropertyChanging();
					this._DEPARTED_DATETIME = value;
					this.SendPropertyChanged("DEPARTED_DATETIME");
					this.OnDEPARTED_DATETIMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DEPARTED_PIECES", DbType="Int")]
		public System.Nullable<int> DEPARTED_PIECES
		{
			get
			{
				return this._DEPARTED_PIECES;
			}
			set
			{
				if ((this._DEPARTED_PIECES != value))
				{
					this.OnDEPARTED_PIECESChanging(value);
					this.SendPropertyChanging();
					this._DEPARTED_PIECES = value;
					this.SendPropertyChanged("DEPARTED_PIECES");
					this.OnDEPARTED_PIECESChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CREATED_AT", DbType="DateTime")]
		public System.Nullable<System.DateTime> CREATED_AT
		{
			get
			{
				return this._CREATED_AT;
			}
			set
			{
				if ((this._CREATED_AT != value))
				{
					this.OnCREATED_ATChanging(value);
					this.SendPropertyChanging();
					this._CREATED_AT = value;
					this.SendPropertyChanged("CREATED_AT");
					this.OnCREATED_ATChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LAST_CHANGED_AT", DbType="DateTime")]
		public System.Nullable<System.DateTime> LAST_CHANGED_AT
		{
			get
			{
				return this._LAST_CHANGED_AT;
			}
			set
			{
				if ((this._LAST_CHANGED_AT != value))
				{
					this.OnLAST_CHANGED_ATChanging(value);
					this.SendPropertyChanging();
					this._LAST_CHANGED_AT = value;
					this.SendPropertyChanged("LAST_CHANGED_AT");
					this.OnLAST_CHANGED_ATChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UPDATED_AT", DbType="DateTime")]
		public System.Nullable<System.DateTime> UPDATED_AT
		{
			get
			{
				return this._UPDATED_AT;
			}
			set
			{
				if ((this._UPDATED_AT != value))
				{
					this.OnUPDATED_ATChanging(value);
					this.SendPropertyChanging();
					this._UPDATED_AT = value;
					this.SendPropertyChanged("UPDATED_AT");
					this.OnUPDATED_ATChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UPDATED_BOOKING", DbType="DateTime")]
		public System.Nullable<System.DateTime> UPDATED_BOOKING
		{
			get
			{
				return this._UPDATED_BOOKING;
			}
			set
			{
				if ((this._UPDATED_BOOKING != value))
				{
					this.OnUPDATED_BOOKINGChanging(value);
					this.SendPropertyChanging();
					this._UPDATED_BOOKING = value;
					this.SendPropertyChanged("UPDATED_BOOKING");
					this.OnUPDATED_BOOKINGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SHC", DbType="VarChar(50)")]
		public string SHC
		{
			get
			{
				return this._SHC;
			}
			set
			{
				if ((this._SHC != value))
				{
					this.OnSHCChanging(value);
					this.SendPropertyChanging();
					this._SHC = value;
					this.SendPropertyChanged("SHC");
					this.OnSHCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WEIGHT", DbType="VarChar(50)")]
		public string WEIGHT
		{
			get
			{
				return this._WEIGHT;
			}
			set
			{
				if ((this._WEIGHT != value))
				{
					this.OnWEIGHTChanging(value);
					this.SendPropertyChanging();
					this._WEIGHT = value;
					this.SendPropertyChanged("WEIGHT");
					this.OnWEIGHTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_USER_ACTION", DbType="VarChar(50)")]
		public string USER_ACTION
		{
			get
			{
				return this._USER_ACTION;
			}
			set
			{
				if ((this._USER_ACTION != value))
				{
					this.OnUSER_ACTIONChanging(value);
					this.SendPropertyChanging();
					this._USER_ACTION = value;
					this.SendPropertyChanged("USER_ACTION");
					this.OnUSER_ACTIONChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
