#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TASK.DATA
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="ALSC_SyncData")]
	public partial class DBContextDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertCarNumber(CarNumber instance);
    partial void UpdateCarNumber(CarNumber instance);
    partial void DeleteCarNumber(CarNumber instance);
    partial void InsertCondition(Condition instance);
    partial void UpdateCondition(Condition instance);
    partial void DeleteCondition(Condition instance);
    partial void Insertform(form instance);
    partial void Updateform(form instance);
    partial void Deleteform(form instance);
    partial void InsertIssue(Issue instance);
    partial void UpdateIssue(Issue instance);
    partial void DeleteIssue(Issue instance);
    partial void InsertLog(Log instance);
    partial void UpdateLog(Log instance);
    partial void DeleteLog(Log instance);
    partial void InsertIssue_detail(Issue_detail instance);
    partial void UpdateIssue_detail(Issue_detail instance);
    partial void DeleteIssue_detail(Issue_detail instance);
    partial void InsertVCT(VCT instance);
    partial void UpdateVCT(VCT instance);
    partial void DeleteVCT(VCT instance);
    partial void InsertFLightFlup(FLightFlup instance);
    partial void UpdateFLightFlup(FLightFlup instance);
    partial void DeleteFLightFlup(FLightFlup instance);
    #endregion
		
		public DBContextDataContext() : 
				base(global::TASK.DATA.Properties.Settings.Default.ALSC_SyncDataConnectionString3, mappingSource)
		{
			OnCreated();
		}
		
		public DBContextDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DBContextDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DBContextDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DBContextDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<CarNumber> CarNumbers
		{
			get
			{
				return this.GetTable<CarNumber>();
			}
		}
		
		public System.Data.Linq.Table<Condition> Conditions
		{
			get
			{
				return this.GetTable<Condition>();
			}
		}
		
		public System.Data.Linq.Table<form> forms
		{
			get
			{
				return this.GetTable<form>();
			}
		}
		
		public System.Data.Linq.Table<Issue> Issues
		{
			get
			{
				return this.GetTable<Issue>();
			}
		}
		
		public System.Data.Linq.Table<Log> Logs
		{
			get
			{
				return this.GetTable<Log>();
			}
		}
		
		public System.Data.Linq.Table<Issue_detail> Issue_details
		{
			get
			{
				return this.GetTable<Issue_detail>();
			}
		}
		
		public System.Data.Linq.Table<VCT> VCTs
		{
			get
			{
				return this.GetTable<VCT>();
			}
		}
		
		public System.Data.Linq.Table<FLightFlup> FLightFlups
		{
			get
			{
				return this.GetTable<FLightFlup>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CarNumber")]
	public partial class CarNumber : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _CarNumber1;
		
		private System.Nullable<int> _IssueID;
		
		private string _IssueKey;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnCarNumber1Changing(string value);
    partial void OnCarNumber1Changed();
    partial void OnIssueIDChanging(System.Nullable<int> value);
    partial void OnIssueIDChanged();
    partial void OnIssueKeyChanging(string value);
    partial void OnIssueKeyChanged();
    #endregion
		
		public CarNumber()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="CarNumber", Storage="_CarNumber1", DbType="VarChar(50)")]
		public string CarNumber1
		{
			get
			{
				return this._CarNumber1;
			}
			set
			{
				if ((this._CarNumber1 != value))
				{
					this.OnCarNumber1Changing(value);
					this.SendPropertyChanging();
					this._CarNumber1 = value;
					this.SendPropertyChanged("CarNumber1");
					this.OnCarNumber1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IssueID", DbType="Int")]
		public System.Nullable<int> IssueID
		{
			get
			{
				return this._IssueID;
			}
			set
			{
				if ((this._IssueID != value))
				{
					this.OnIssueIDChanging(value);
					this.SendPropertyChanging();
					this._IssueID = value;
					this.SendPropertyChanged("IssueID");
					this.OnIssueIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IssueKey", DbType="VarChar(50)")]
		public string IssueKey
		{
			get
			{
				return this._IssueKey;
			}
			set
			{
				if ((this._IssueKey != value))
				{
					this.OnIssueKeyChanging(value);
					this.SendPropertyChanging();
					this._IssueKey = value;
					this.SendPropertyChanged("IssueKey");
					this.OnIssueKeyChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Condition")]
	public partial class Condition : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _name;
		
		private System.Nullable<bool> _checked;
		
		private System.Nullable<bool> _mandatory;
		
		private System.Nullable<bool> _option;
		
		private System.Nullable<int> _id_condittion;
		
		private System.Nullable<int> _rank;
		
		private System.Nullable<int> _issue_id;
		
		private string _issue_key;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnnameChanging(string value);
    partial void OnnameChanged();
    partial void OncheckedChanging(System.Nullable<bool> value);
    partial void OncheckedChanged();
    partial void OnmandatoryChanging(System.Nullable<bool> value);
    partial void OnmandatoryChanged();
    partial void OnoptionChanging(System.Nullable<bool> value);
    partial void OnoptionChanged();
    partial void Onid_condittionChanging(System.Nullable<int> value);
    partial void Onid_condittionChanged();
    partial void OnrankChanging(System.Nullable<int> value);
    partial void OnrankChanged();
    partial void Onissue_idChanging(System.Nullable<int> value);
    partial void Onissue_idChanged();
    partial void Onissue_keyChanging(string value);
    partial void Onissue_keyChanged();
    #endregion
		
		public Condition()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="NVarChar(50)")]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this.OnnameChanging(value);
					this.SendPropertyChanging();
					this._name = value;
					this.SendPropertyChanged("name");
					this.OnnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="checked", Storage="_checked", DbType="Bit")]
		public System.Nullable<bool> @checked
		{
			get
			{
				return this._checked;
			}
			set
			{
				if ((this._checked != value))
				{
					this.OncheckedChanging(value);
					this.SendPropertyChanging();
					this._checked = value;
					this.SendPropertyChanged("@checked");
					this.OncheckedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mandatory", DbType="Bit")]
		public System.Nullable<bool> mandatory
		{
			get
			{
				return this._mandatory;
			}
			set
			{
				if ((this._mandatory != value))
				{
					this.OnmandatoryChanging(value);
					this.SendPropertyChanging();
					this._mandatory = value;
					this.SendPropertyChanged("mandatory");
					this.OnmandatoryChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[option]", Storage="_option", DbType="Bit")]
		public System.Nullable<bool> option
		{
			get
			{
				return this._option;
			}
			set
			{
				if ((this._option != value))
				{
					this.OnoptionChanging(value);
					this.SendPropertyChanging();
					this._option = value;
					this.SendPropertyChanged("option");
					this.OnoptionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_condittion", DbType="Int")]
		public System.Nullable<int> id_condittion
		{
			get
			{
				return this._id_condittion;
			}
			set
			{
				if ((this._id_condittion != value))
				{
					this.Onid_condittionChanging(value);
					this.SendPropertyChanging();
					this._id_condittion = value;
					this.SendPropertyChanged("id_condittion");
					this.Onid_condittionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_rank", DbType="Int")]
		public System.Nullable<int> rank
		{
			get
			{
				return this._rank;
			}
			set
			{
				if ((this._rank != value))
				{
					this.OnrankChanging(value);
					this.SendPropertyChanging();
					this._rank = value;
					this.SendPropertyChanged("rank");
					this.OnrankChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_issue_id", DbType="Int")]
		public System.Nullable<int> issue_id
		{
			get
			{
				return this._issue_id;
			}
			set
			{
				if ((this._issue_id != value))
				{
					this.Onissue_idChanging(value);
					this.SendPropertyChanging();
					this._issue_id = value;
					this.SendPropertyChanged("issue_id");
					this.Onissue_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_issue_key", DbType="VarChar(50)")]
		public string issue_key
		{
			get
			{
				return this._issue_key;
			}
			set
			{
				if ((this._issue_key != value))
				{
					this.Onissue_keyChanging(value);
					this.SendPropertyChanging();
					this._issue_key = value;
					this.SendPropertyChanged("issue_key");
					this.Onissue_keyChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.form")]
	public partial class form : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _author;
		
		private string _AWB;
		
		private string _quantity;
		
		private string _weight;
		
		private string _booking;
		
		private System.Nullable<bool> _custom_status;
		
		private string _car_number;
		
		private string _phone_number;
		
		private string _email;
		
		private string _issue_key;
		
		private System.Nullable<System.DateTime> _createdDate;
		
		private System.Nullable<System.DateTime> _lastUpdated;
		
		private System.Nullable<System.DateTime> _CutoffTime;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnauthorChanging(string value);
    partial void OnauthorChanged();
    partial void OnAWBChanging(string value);
    partial void OnAWBChanged();
    partial void OnquantityChanging(string value);
    partial void OnquantityChanged();
    partial void OnweightChanging(string value);
    partial void OnweightChanged();
    partial void OnbookingChanging(string value);
    partial void OnbookingChanged();
    partial void Oncustom_statusChanging(System.Nullable<bool> value);
    partial void Oncustom_statusChanged();
    partial void Oncar_numberChanging(string value);
    partial void Oncar_numberChanged();
    partial void Onphone_numberChanging(string value);
    partial void Onphone_numberChanged();
    partial void OnemailChanging(string value);
    partial void OnemailChanged();
    partial void Onissue_keyChanging(string value);
    partial void Onissue_keyChanged();
    partial void OncreatedDateChanging(System.Nullable<System.DateTime> value);
    partial void OncreatedDateChanged();
    partial void OnlastUpdatedChanging(System.Nullable<System.DateTime> value);
    partial void OnlastUpdatedChanged();
    partial void OnCutoffTimeChanging(System.Nullable<System.DateTime> value);
    partial void OnCutoffTimeChanged();
    #endregion
		
		public form()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_author", DbType="VarChar(50)")]
		public string author
		{
			get
			{
				return this._author;
			}
			set
			{
				if ((this._author != value))
				{
					this.OnauthorChanging(value);
					this.SendPropertyChanging();
					this._author = value;
					this.SendPropertyChanged("author");
					this.OnauthorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AWB", DbType="VarChar(50)")]
		public string AWB
		{
			get
			{
				return this._AWB;
			}
			set
			{
				if ((this._AWB != value))
				{
					this.OnAWBChanging(value);
					this.SendPropertyChanging();
					this._AWB = value;
					this.SendPropertyChanged("AWB");
					this.OnAWBChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_quantity", DbType="VarChar(50)")]
		public string quantity
		{
			get
			{
				return this._quantity;
			}
			set
			{
				if ((this._quantity != value))
				{
					this.OnquantityChanging(value);
					this.SendPropertyChanging();
					this._quantity = value;
					this.SendPropertyChanged("quantity");
					this.OnquantityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_weight", DbType="VarChar(50)")]
		public string weight
		{
			get
			{
				return this._weight;
			}
			set
			{
				if ((this._weight != value))
				{
					this.OnweightChanging(value);
					this.SendPropertyChanging();
					this._weight = value;
					this.SendPropertyChanged("weight");
					this.OnweightChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_booking", DbType="VarChar(50)")]
		public string booking
		{
			get
			{
				return this._booking;
			}
			set
			{
				if ((this._booking != value))
				{
					this.OnbookingChanging(value);
					this.SendPropertyChanging();
					this._booking = value;
					this.SendPropertyChanged("booking");
					this.OnbookingChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_custom_status", DbType="Bit")]
		public System.Nullable<bool> custom_status
		{
			get
			{
				return this._custom_status;
			}
			set
			{
				if ((this._custom_status != value))
				{
					this.Oncustom_statusChanging(value);
					this.SendPropertyChanging();
					this._custom_status = value;
					this.SendPropertyChanged("custom_status");
					this.Oncustom_statusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_car_number", DbType="VarChar(50)")]
		public string car_number
		{
			get
			{
				return this._car_number;
			}
			set
			{
				if ((this._car_number != value))
				{
					this.Oncar_numberChanging(value);
					this.SendPropertyChanging();
					this._car_number = value;
					this.SendPropertyChanged("car_number");
					this.Oncar_numberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_phone_number", DbType="VarChar(50)")]
		public string phone_number
		{
			get
			{
				return this._phone_number;
			}
			set
			{
				if ((this._phone_number != value))
				{
					this.Onphone_numberChanging(value);
					this.SendPropertyChanging();
					this._phone_number = value;
					this.SendPropertyChanged("phone_number");
					this.Onphone_numberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_email", DbType="VarChar(50)")]
		public string email
		{
			get
			{
				return this._email;
			}
			set
			{
				if ((this._email != value))
				{
					this.OnemailChanging(value);
					this.SendPropertyChanging();
					this._email = value;
					this.SendPropertyChanged("email");
					this.OnemailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_issue_key", DbType="VarChar(50)")]
		public string issue_key
		{
			get
			{
				return this._issue_key;
			}
			set
			{
				if ((this._issue_key != value))
				{
					this.Onissue_keyChanging(value);
					this.SendPropertyChanging();
					this._issue_key = value;
					this.SendPropertyChanged("issue_key");
					this.Onissue_keyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_createdDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> createdDate
		{
			get
			{
				return this._createdDate;
			}
			set
			{
				if ((this._createdDate != value))
				{
					this.OncreatedDateChanging(value);
					this.SendPropertyChanging();
					this._createdDate = value;
					this.SendPropertyChanged("createdDate");
					this.OncreatedDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lastUpdated", DbType="DateTime")]
		public System.Nullable<System.DateTime> lastUpdated
		{
			get
			{
				return this._lastUpdated;
			}
			set
			{
				if ((this._lastUpdated != value))
				{
					this.OnlastUpdatedChanging(value);
					this.SendPropertyChanging();
					this._lastUpdated = value;
					this.SendPropertyChanged("lastUpdated");
					this.OnlastUpdatedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CutoffTime", DbType="DateTime")]
		public System.Nullable<System.DateTime> CutoffTime
		{
			get
			{
				return this._CutoffTime;
			}
			set
			{
				if ((this._CutoffTime != value))
				{
					this.OnCutoffTimeChanging(value);
					this.SendPropertyChanging();
					this._CutoffTime = value;
					this.SendPropertyChanged("CutoffTime");
					this.OnCutoffTimeChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.IssueS")]
	public partial class Issue : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _key;
		
		private string _self;
		
		private string _fields_summary;
		
		private System.Nullable<System.DateTime> _fields_duedate;
		
		private System.Nullable<System.DateTime> _fields_created;
		
		private string _fields_reporter_displayName;
		
		private string _fields_issuetype_description;
		
		private string _fields_issuetype_name;
		
		private string _fields_status_name;
		
		private System.Nullable<int> _fields_status_id;
		
		private string _fields_status_statusCategory_name;
		
		private System.Nullable<int> _fields_status_statusCategory_id;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnkeyChanging(string value);
    partial void OnkeyChanged();
    partial void OnselfChanging(string value);
    partial void OnselfChanged();
    partial void Onfields_summaryChanging(string value);
    partial void Onfields_summaryChanged();
    partial void Onfields_duedateChanging(System.Nullable<System.DateTime> value);
    partial void Onfields_duedateChanged();
    partial void Onfields_createdChanging(System.Nullable<System.DateTime> value);
    partial void Onfields_createdChanged();
    partial void Onfields_reporter_displayNameChanging(string value);
    partial void Onfields_reporter_displayNameChanged();
    partial void Onfields_issuetype_descriptionChanging(string value);
    partial void Onfields_issuetype_descriptionChanged();
    partial void Onfields_issuetype_nameChanging(string value);
    partial void Onfields_issuetype_nameChanged();
    partial void Onfields_status_nameChanging(string value);
    partial void Onfields_status_nameChanged();
    partial void Onfields_status_idChanging(System.Nullable<int> value);
    partial void Onfields_status_idChanged();
    partial void Onfields_status_statusCategory_nameChanging(string value);
    partial void Onfields_status_statusCategory_nameChanged();
    partial void Onfields_status_statusCategory_idChanging(System.Nullable<int> value);
    partial void Onfields_status_statusCategory_idChanged();
    #endregion
		
		public Issue()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[key]", Storage="_key", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string key
		{
			get
			{
				return this._key;
			}
			set
			{
				if ((this._key != value))
				{
					this.OnkeyChanging(value);
					this.SendPropertyChanging();
					this._key = value;
					this.SendPropertyChanged("key");
					this.OnkeyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_self", DbType="VarChar(200)")]
		public string self
		{
			get
			{
				return this._self;
			}
			set
			{
				if ((this._self != value))
				{
					this.OnselfChanging(value);
					this.SendPropertyChanging();
					this._self = value;
					this.SendPropertyChanged("self");
					this.OnselfChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fields_summary", DbType="NVarChar(500)")]
		public string fields_summary
		{
			get
			{
				return this._fields_summary;
			}
			set
			{
				if ((this._fields_summary != value))
				{
					this.Onfields_summaryChanging(value);
					this.SendPropertyChanging();
					this._fields_summary = value;
					this.SendPropertyChanged("fields_summary");
					this.Onfields_summaryChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fields_duedate", DbType="DateTime")]
		public System.Nullable<System.DateTime> fields_duedate
		{
			get
			{
				return this._fields_duedate;
			}
			set
			{
				if ((this._fields_duedate != value))
				{
					this.Onfields_duedateChanging(value);
					this.SendPropertyChanging();
					this._fields_duedate = value;
					this.SendPropertyChanged("fields_duedate");
					this.Onfields_duedateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fields_created", DbType="DateTime")]
		public System.Nullable<System.DateTime> fields_created
		{
			get
			{
				return this._fields_created;
			}
			set
			{
				if ((this._fields_created != value))
				{
					this.Onfields_createdChanging(value);
					this.SendPropertyChanging();
					this._fields_created = value;
					this.SendPropertyChanged("fields_created");
					this.Onfields_createdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fields_reporter_displayName", DbType="NVarChar(50)")]
		public string fields_reporter_displayName
		{
			get
			{
				return this._fields_reporter_displayName;
			}
			set
			{
				if ((this._fields_reporter_displayName != value))
				{
					this.Onfields_reporter_displayNameChanging(value);
					this.SendPropertyChanging();
					this._fields_reporter_displayName = value;
					this.SendPropertyChanged("fields_reporter_displayName");
					this.Onfields_reporter_displayNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fields_issuetype_description", DbType="NVarChar(500)")]
		public string fields_issuetype_description
		{
			get
			{
				return this._fields_issuetype_description;
			}
			set
			{
				if ((this._fields_issuetype_description != value))
				{
					this.Onfields_issuetype_descriptionChanging(value);
					this.SendPropertyChanging();
					this._fields_issuetype_description = value;
					this.SendPropertyChanged("fields_issuetype_description");
					this.Onfields_issuetype_descriptionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fields_issuetype_name", DbType="NVarChar(50)")]
		public string fields_issuetype_name
		{
			get
			{
				return this._fields_issuetype_name;
			}
			set
			{
				if ((this._fields_issuetype_name != value))
				{
					this.Onfields_issuetype_nameChanging(value);
					this.SendPropertyChanging();
					this._fields_issuetype_name = value;
					this.SendPropertyChanged("fields_issuetype_name");
					this.Onfields_issuetype_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fields_status_name", DbType="NVarChar(50)")]
		public string fields_status_name
		{
			get
			{
				return this._fields_status_name;
			}
			set
			{
				if ((this._fields_status_name != value))
				{
					this.Onfields_status_nameChanging(value);
					this.SendPropertyChanging();
					this._fields_status_name = value;
					this.SendPropertyChanged("fields_status_name");
					this.Onfields_status_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fields_status_id", DbType="Int")]
		public System.Nullable<int> fields_status_id
		{
			get
			{
				return this._fields_status_id;
			}
			set
			{
				if ((this._fields_status_id != value))
				{
					this.Onfields_status_idChanging(value);
					this.SendPropertyChanging();
					this._fields_status_id = value;
					this.SendPropertyChanged("fields_status_id");
					this.Onfields_status_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fields_status_statusCategory_name", DbType="VarChar(50)")]
		public string fields_status_statusCategory_name
		{
			get
			{
				return this._fields_status_statusCategory_name;
			}
			set
			{
				if ((this._fields_status_statusCategory_name != value))
				{
					this.Onfields_status_statusCategory_nameChanging(value);
					this.SendPropertyChanging();
					this._fields_status_statusCategory_name = value;
					this.SendPropertyChanged("fields_status_statusCategory_name");
					this.Onfields_status_statusCategory_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fields_status_statusCategory_id", DbType="Int")]
		public System.Nullable<int> fields_status_statusCategory_id
		{
			get
			{
				return this._fields_status_statusCategory_id;
			}
			set
			{
				if ((this._fields_status_statusCategory_id != value))
				{
					this.Onfields_status_statusCategory_idChanging(value);
					this.SendPropertyChanging();
					this._fields_status_statusCategory_id = value;
					this.SendPropertyChanged("fields_status_statusCategory_id");
					this.Onfields_status_statusCategory_idChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.[Log]")]
	public partial class Log : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _LogID;
		
		private string _LogType;
		
		private string _LogMessage;
		
		private System.Nullable<System.DateTime> _LogTime;
		
		private string _LogTrace;
		
		private string _LogSource;
		
		private System.Nullable<bool> _Status;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnLogIDChanging(int value);
    partial void OnLogIDChanged();
    partial void OnLogTypeChanging(string value);
    partial void OnLogTypeChanged();
    partial void OnLogMessageChanging(string value);
    partial void OnLogMessageChanged();
    partial void OnLogTimeChanging(System.Nullable<System.DateTime> value);
    partial void OnLogTimeChanged();
    partial void OnLogTraceChanging(string value);
    partial void OnLogTraceChanged();
    partial void OnLogSourceChanging(string value);
    partial void OnLogSourceChanged();
    partial void OnStatusChanging(System.Nullable<bool> value);
    partial void OnStatusChanged();
    #endregion
		
		public Log()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LogID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int LogID
		{
			get
			{
				return this._LogID;
			}
			set
			{
				if ((this._LogID != value))
				{
					this.OnLogIDChanging(value);
					this.SendPropertyChanging();
					this._LogID = value;
					this.SendPropertyChanged("LogID");
					this.OnLogIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LogType", DbType="VarChar(50)")]
		public string LogType
		{
			get
			{
				return this._LogType;
			}
			set
			{
				if ((this._LogType != value))
				{
					this.OnLogTypeChanging(value);
					this.SendPropertyChanging();
					this._LogType = value;
					this.SendPropertyChanged("LogType");
					this.OnLogTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LogMessage", DbType="VarChar(500)")]
		public string LogMessage
		{
			get
			{
				return this._LogMessage;
			}
			set
			{
				if ((this._LogMessage != value))
				{
					this.OnLogMessageChanging(value);
					this.SendPropertyChanging();
					this._LogMessage = value;
					this.SendPropertyChanged("LogMessage");
					this.OnLogMessageChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LogTime", DbType="DateTime")]
		public System.Nullable<System.DateTime> LogTime
		{
			get
			{
				return this._LogTime;
			}
			set
			{
				if ((this._LogTime != value))
				{
					this.OnLogTimeChanging(value);
					this.SendPropertyChanging();
					this._LogTime = value;
					this.SendPropertyChanged("LogTime");
					this.OnLogTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LogTrace", DbType="VarChar(500)")]
		public string LogTrace
		{
			get
			{
				return this._LogTrace;
			}
			set
			{
				if ((this._LogTrace != value))
				{
					this.OnLogTraceChanging(value);
					this.SendPropertyChanging();
					this._LogTrace = value;
					this.SendPropertyChanged("LogTrace");
					this.OnLogTraceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LogSource", DbType="VarChar(50)")]
		public string LogSource
		{
			get
			{
				return this._LogSource;
			}
			set
			{
				if ((this._LogSource != value))
				{
					this.OnLogSourceChanging(value);
					this.SendPropertyChanging();
					this._LogSource = value;
					this.SendPropertyChanged("LogSource");
					this.OnLogSourceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Status", DbType="Bit")]
		public System.Nullable<bool> Status
		{
			get
			{
				return this._Status;
			}
			set
			{
				if ((this._Status != value))
				{
					this.OnStatusChanging(value);
					this.SendPropertyChanging();
					this._Status = value;
					this.SendPropertyChanged("Status");
					this.OnStatusChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Issue_detail")]
	public partial class Issue_detail : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _key;
		
		private string _self;
		
		private string _fields_fixVersions_name;
		
		private System.Nullable<System.DateTime> _fields_lastViewed;
		
		private string _fields_priority_name;
		
		private System.Nullable<int> _fields_priority_id;
		
		private string _fields_assignee_emailAddress;
		
		private string _fields_assignee_displayName;
		
		private string _fields_status_name;
		
		private System.Nullable<int> _fields_status_statusCategory_id;
		
		private string _fields_status_statusCategory_key;
		
		private string _fields_status_statusCategory_name;
		
		private string _fields_status_statusCategory_colorName;
		
		private string _fields_creator_name;
		
		private string _fields_creator_displayName;
		
		private string _fields_reporter_name;
		
		private string _fields_reporter_displayName;
		
		private System.Nullable<System.DateTime> _fields_created;
		
		private string _fields_summary;
		
		private System.Nullable<System.DateTime> _fields_duedate;
		
		private System.Nullable<int> _fields_status_id;
		
		private string _DriverName;
		
		private string _DriverID;
		
		private string _Introduction;
		
		private string _pieces;
		
		private string _weight;
		
		private string _AWB;
		
		private string _Dest;
		
		private string _Booking;
		
		private string _Agent;
		
		private string _PhoneNumber;
		
		private System.Nullable<System.DateTime> _CutoffTime;
		
		private string _Comment;
		
		private System.Nullable<System.DateTime> _TimeTransition;
		
		private System.Nullable<System.DateTime> _Created;
		
		private System.Nullable<int> _SortValue;
		
		private string _FlightType;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnkeyChanging(string value);
    partial void OnkeyChanged();
    partial void OnselfChanging(string value);
    partial void OnselfChanged();
    partial void Onfields_fixVersions_nameChanging(string value);
    partial void Onfields_fixVersions_nameChanged();
    partial void Onfields_lastViewedChanging(System.Nullable<System.DateTime> value);
    partial void Onfields_lastViewedChanged();
    partial void Onfields_priority_nameChanging(string value);
    partial void Onfields_priority_nameChanged();
    partial void Onfields_priority_idChanging(System.Nullable<int> value);
    partial void Onfields_priority_idChanged();
    partial void Onfields_assignee_emailAddressChanging(string value);
    partial void Onfields_assignee_emailAddressChanged();
    partial void Onfields_assignee_displayNameChanging(string value);
    partial void Onfields_assignee_displayNameChanged();
    partial void Onfields_status_nameChanging(string value);
    partial void Onfields_status_nameChanged();
    partial void Onfields_status_statusCategory_idChanging(System.Nullable<int> value);
    partial void Onfields_status_statusCategory_idChanged();
    partial void Onfields_status_statusCategory_keyChanging(string value);
    partial void Onfields_status_statusCategory_keyChanged();
    partial void Onfields_status_statusCategory_nameChanging(string value);
    partial void Onfields_status_statusCategory_nameChanged();
    partial void Onfields_status_statusCategory_colorNameChanging(string value);
    partial void Onfields_status_statusCategory_colorNameChanged();
    partial void Onfields_creator_nameChanging(string value);
    partial void Onfields_creator_nameChanged();
    partial void Onfields_creator_displayNameChanging(string value);
    partial void Onfields_creator_displayNameChanged();
    partial void Onfields_reporter_nameChanging(string value);
    partial void Onfields_reporter_nameChanged();
    partial void Onfields_reporter_displayNameChanging(string value);
    partial void Onfields_reporter_displayNameChanged();
    partial void Onfields_createdChanging(System.Nullable<System.DateTime> value);
    partial void Onfields_createdChanged();
    partial void Onfields_summaryChanging(string value);
    partial void Onfields_summaryChanged();
    partial void Onfields_duedateChanging(System.Nullable<System.DateTime> value);
    partial void Onfields_duedateChanged();
    partial void Onfields_status_idChanging(System.Nullable<int> value);
    partial void Onfields_status_idChanged();
    partial void OnDriverNameChanging(string value);
    partial void OnDriverNameChanged();
    partial void OnDriverIDChanging(string value);
    partial void OnDriverIDChanged();
    partial void OnIntroductionChanging(string value);
    partial void OnIntroductionChanged();
    partial void OnpiecesChanging(string value);
    partial void OnpiecesChanged();
    partial void OnweightChanging(string value);
    partial void OnweightChanged();
    partial void OnAWBChanging(string value);
    partial void OnAWBChanged();
    partial void OnDestChanging(string value);
    partial void OnDestChanged();
    partial void OnBookingChanging(string value);
    partial void OnBookingChanged();
    partial void OnAgentChanging(string value);
    partial void OnAgentChanged();
    partial void OnPhoneNumberChanging(string value);
    partial void OnPhoneNumberChanged();
    partial void OnCutoffTimeChanging(System.Nullable<System.DateTime> value);
    partial void OnCutoffTimeChanged();
    partial void OnCommentChanging(string value);
    partial void OnCommentChanged();
    partial void OnTimeTransitionChanging(System.Nullable<System.DateTime> value);
    partial void OnTimeTransitionChanged();
    partial void OnCreatedChanging(System.Nullable<System.DateTime> value);
    partial void OnCreatedChanged();
    partial void OnSortValueChanging(System.Nullable<int> value);
    partial void OnSortValueChanged();
    partial void OnFlightTypeChanging(string value);
    partial void OnFlightTypeChanged();
    #endregion
		
		public Issue_detail()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[key]", Storage="_key", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string key
		{
			get
			{
				return this._key;
			}
			set
			{
				if ((this._key != value))
				{
					this.OnkeyChanging(value);
					this.SendPropertyChanging();
					this._key = value;
					this.SendPropertyChanged("key");
					this.OnkeyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_self", DbType="VarChar(200)")]
		public string self
		{
			get
			{
				return this._self;
			}
			set
			{
				if ((this._self != value))
				{
					this.OnselfChanging(value);
					this.SendPropertyChanging();
					this._self = value;
					this.SendPropertyChanged("self");
					this.OnselfChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fields_fixVersions_name", DbType="NVarChar(50)")]
		public string fields_fixVersions_name
		{
			get
			{
				return this._fields_fixVersions_name;
			}
			set
			{
				if ((this._fields_fixVersions_name != value))
				{
					this.Onfields_fixVersions_nameChanging(value);
					this.SendPropertyChanging();
					this._fields_fixVersions_name = value;
					this.SendPropertyChanged("fields_fixVersions_name");
					this.Onfields_fixVersions_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fields_lastViewed", DbType="DateTime")]
		public System.Nullable<System.DateTime> fields_lastViewed
		{
			get
			{
				return this._fields_lastViewed;
			}
			set
			{
				if ((this._fields_lastViewed != value))
				{
					this.Onfields_lastViewedChanging(value);
					this.SendPropertyChanging();
					this._fields_lastViewed = value;
					this.SendPropertyChanged("fields_lastViewed");
					this.Onfields_lastViewedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fields_priority_name", DbType="VarChar(50)")]
		public string fields_priority_name
		{
			get
			{
				return this._fields_priority_name;
			}
			set
			{
				if ((this._fields_priority_name != value))
				{
					this.Onfields_priority_nameChanging(value);
					this.SendPropertyChanging();
					this._fields_priority_name = value;
					this.SendPropertyChanged("fields_priority_name");
					this.Onfields_priority_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fields_priority_id", DbType="Int")]
		public System.Nullable<int> fields_priority_id
		{
			get
			{
				return this._fields_priority_id;
			}
			set
			{
				if ((this._fields_priority_id != value))
				{
					this.Onfields_priority_idChanging(value);
					this.SendPropertyChanging();
					this._fields_priority_id = value;
					this.SendPropertyChanged("fields_priority_id");
					this.Onfields_priority_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fields_assignee_emailAddress", DbType="VarChar(50)")]
		public string fields_assignee_emailAddress
		{
			get
			{
				return this._fields_assignee_emailAddress;
			}
			set
			{
				if ((this._fields_assignee_emailAddress != value))
				{
					this.Onfields_assignee_emailAddressChanging(value);
					this.SendPropertyChanging();
					this._fields_assignee_emailAddress = value;
					this.SendPropertyChanged("fields_assignee_emailAddress");
					this.Onfields_assignee_emailAddressChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fields_assignee_displayName", DbType="NVarChar(200)")]
		public string fields_assignee_displayName
		{
			get
			{
				return this._fields_assignee_displayName;
			}
			set
			{
				if ((this._fields_assignee_displayName != value))
				{
					this.Onfields_assignee_displayNameChanging(value);
					this.SendPropertyChanging();
					this._fields_assignee_displayName = value;
					this.SendPropertyChanged("fields_assignee_displayName");
					this.Onfields_assignee_displayNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fields_status_name", DbType="NVarChar(200)")]
		public string fields_status_name
		{
			get
			{
				return this._fields_status_name;
			}
			set
			{
				if ((this._fields_status_name != value))
				{
					this.Onfields_status_nameChanging(value);
					this.SendPropertyChanging();
					this._fields_status_name = value;
					this.SendPropertyChanged("fields_status_name");
					this.Onfields_status_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fields_status_statusCategory_id", DbType="Int")]
		public System.Nullable<int> fields_status_statusCategory_id
		{
			get
			{
				return this._fields_status_statusCategory_id;
			}
			set
			{
				if ((this._fields_status_statusCategory_id != value))
				{
					this.Onfields_status_statusCategory_idChanging(value);
					this.SendPropertyChanging();
					this._fields_status_statusCategory_id = value;
					this.SendPropertyChanged("fields_status_statusCategory_id");
					this.Onfields_status_statusCategory_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fields_status_statusCategory_key", DbType="VarChar(50)")]
		public string fields_status_statusCategory_key
		{
			get
			{
				return this._fields_status_statusCategory_key;
			}
			set
			{
				if ((this._fields_status_statusCategory_key != value))
				{
					this.Onfields_status_statusCategory_keyChanging(value);
					this.SendPropertyChanging();
					this._fields_status_statusCategory_key = value;
					this.SendPropertyChanged("fields_status_statusCategory_key");
					this.Onfields_status_statusCategory_keyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fields_status_statusCategory_name", DbType="VarChar(50)")]
		public string fields_status_statusCategory_name
		{
			get
			{
				return this._fields_status_statusCategory_name;
			}
			set
			{
				if ((this._fields_status_statusCategory_name != value))
				{
					this.Onfields_status_statusCategory_nameChanging(value);
					this.SendPropertyChanging();
					this._fields_status_statusCategory_name = value;
					this.SendPropertyChanged("fields_status_statusCategory_name");
					this.Onfields_status_statusCategory_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fields_status_statusCategory_colorName", DbType="VarChar(50)")]
		public string fields_status_statusCategory_colorName
		{
			get
			{
				return this._fields_status_statusCategory_colorName;
			}
			set
			{
				if ((this._fields_status_statusCategory_colorName != value))
				{
					this.Onfields_status_statusCategory_colorNameChanging(value);
					this.SendPropertyChanging();
					this._fields_status_statusCategory_colorName = value;
					this.SendPropertyChanged("fields_status_statusCategory_colorName");
					this.Onfields_status_statusCategory_colorNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fields_creator_name", DbType="VarChar(50)")]
		public string fields_creator_name
		{
			get
			{
				return this._fields_creator_name;
			}
			set
			{
				if ((this._fields_creator_name != value))
				{
					this.Onfields_creator_nameChanging(value);
					this.SendPropertyChanging();
					this._fields_creator_name = value;
					this.SendPropertyChanged("fields_creator_name");
					this.Onfields_creator_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fields_creator_displayName", DbType="NVarChar(200)")]
		public string fields_creator_displayName
		{
			get
			{
				return this._fields_creator_displayName;
			}
			set
			{
				if ((this._fields_creator_displayName != value))
				{
					this.Onfields_creator_displayNameChanging(value);
					this.SendPropertyChanging();
					this._fields_creator_displayName = value;
					this.SendPropertyChanged("fields_creator_displayName");
					this.Onfields_creator_displayNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fields_reporter_name", DbType="VarChar(50)")]
		public string fields_reporter_name
		{
			get
			{
				return this._fields_reporter_name;
			}
			set
			{
				if ((this._fields_reporter_name != value))
				{
					this.Onfields_reporter_nameChanging(value);
					this.SendPropertyChanging();
					this._fields_reporter_name = value;
					this.SendPropertyChanged("fields_reporter_name");
					this.Onfields_reporter_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fields_reporter_displayName", DbType="NVarChar(200)")]
		public string fields_reporter_displayName
		{
			get
			{
				return this._fields_reporter_displayName;
			}
			set
			{
				if ((this._fields_reporter_displayName != value))
				{
					this.Onfields_reporter_displayNameChanging(value);
					this.SendPropertyChanging();
					this._fields_reporter_displayName = value;
					this.SendPropertyChanged("fields_reporter_displayName");
					this.Onfields_reporter_displayNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fields_created", DbType="DateTime")]
		public System.Nullable<System.DateTime> fields_created
		{
			get
			{
				return this._fields_created;
			}
			set
			{
				if ((this._fields_created != value))
				{
					this.Onfields_createdChanging(value);
					this.SendPropertyChanging();
					this._fields_created = value;
					this.SendPropertyChanged("fields_created");
					this.Onfields_createdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fields_summary", DbType="NVarChar(500)")]
		public string fields_summary
		{
			get
			{
				return this._fields_summary;
			}
			set
			{
				if ((this._fields_summary != value))
				{
					this.Onfields_summaryChanging(value);
					this.SendPropertyChanging();
					this._fields_summary = value;
					this.SendPropertyChanged("fields_summary");
					this.Onfields_summaryChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fields_duedate", DbType="DateTime")]
		public System.Nullable<System.DateTime> fields_duedate
		{
			get
			{
				return this._fields_duedate;
			}
			set
			{
				if ((this._fields_duedate != value))
				{
					this.Onfields_duedateChanging(value);
					this.SendPropertyChanging();
					this._fields_duedate = value;
					this.SendPropertyChanged("fields_duedate");
					this.Onfields_duedateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fields_status_id", DbType="Int")]
		public System.Nullable<int> fields_status_id
		{
			get
			{
				return this._fields_status_id;
			}
			set
			{
				if ((this._fields_status_id != value))
				{
					this.Onfields_status_idChanging(value);
					this.SendPropertyChanging();
					this._fields_status_id = value;
					this.SendPropertyChanged("fields_status_id");
					this.Onfields_status_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DriverName", DbType="NVarChar(50)")]
		public string DriverName
		{
			get
			{
				return this._DriverName;
			}
			set
			{
				if ((this._DriverName != value))
				{
					this.OnDriverNameChanging(value);
					this.SendPropertyChanging();
					this._DriverName = value;
					this.SendPropertyChanged("DriverName");
					this.OnDriverNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DriverID", DbType="VarChar(20)")]
		public string DriverID
		{
			get
			{
				return this._DriverID;
			}
			set
			{
				if ((this._DriverID != value))
				{
					this.OnDriverIDChanging(value);
					this.SendPropertyChanging();
					this._DriverID = value;
					this.SendPropertyChanged("DriverID");
					this.OnDriverIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Introduction", DbType="NVarChar(50)")]
		public string Introduction
		{
			get
			{
				return this._Introduction;
			}
			set
			{
				if ((this._Introduction != value))
				{
					this.OnIntroductionChanging(value);
					this.SendPropertyChanging();
					this._Introduction = value;
					this.SendPropertyChanged("Introduction");
					this.OnIntroductionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pieces", DbType="VarChar(50)")]
		public string pieces
		{
			get
			{
				return this._pieces;
			}
			set
			{
				if ((this._pieces != value))
				{
					this.OnpiecesChanging(value);
					this.SendPropertyChanging();
					this._pieces = value;
					this.SendPropertyChanged("pieces");
					this.OnpiecesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_weight", DbType="VarChar(50)")]
		public string weight
		{
			get
			{
				return this._weight;
			}
			set
			{
				if ((this._weight != value))
				{
					this.OnweightChanging(value);
					this.SendPropertyChanging();
					this._weight = value;
					this.SendPropertyChanged("weight");
					this.OnweightChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AWB", DbType="VarChar(50)")]
		public string AWB
		{
			get
			{
				return this._AWB;
			}
			set
			{
				if ((this._AWB != value))
				{
					this.OnAWBChanging(value);
					this.SendPropertyChanging();
					this._AWB = value;
					this.SendPropertyChanged("AWB");
					this.OnAWBChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Dest", DbType="VarChar(50)")]
		public string Dest
		{
			get
			{
				return this._Dest;
			}
			set
			{
				if ((this._Dest != value))
				{
					this.OnDestChanging(value);
					this.SendPropertyChanging();
					this._Dest = value;
					this.SendPropertyChanged("Dest");
					this.OnDestChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Booking", DbType="VarChar(50)")]
		public string Booking
		{
			get
			{
				return this._Booking;
			}
			set
			{
				if ((this._Booking != value))
				{
					this.OnBookingChanging(value);
					this.SendPropertyChanging();
					this._Booking = value;
					this.SendPropertyChanged("Booking");
					this.OnBookingChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Agent", DbType="NVarChar(200)")]
		public string Agent
		{
			get
			{
				return this._Agent;
			}
			set
			{
				if ((this._Agent != value))
				{
					this.OnAgentChanging(value);
					this.SendPropertyChanging();
					this._Agent = value;
					this.SendPropertyChanged("Agent");
					this.OnAgentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PhoneNumber", DbType="VarChar(50)")]
		public string PhoneNumber
		{
			get
			{
				return this._PhoneNumber;
			}
			set
			{
				if ((this._PhoneNumber != value))
				{
					this.OnPhoneNumberChanging(value);
					this.SendPropertyChanging();
					this._PhoneNumber = value;
					this.SendPropertyChanged("PhoneNumber");
					this.OnPhoneNumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CutoffTime", DbType="DateTime")]
		public System.Nullable<System.DateTime> CutoffTime
		{
			get
			{
				return this._CutoffTime;
			}
			set
			{
				if ((this._CutoffTime != value))
				{
					this.OnCutoffTimeChanging(value);
					this.SendPropertyChanging();
					this._CutoffTime = value;
					this.SendPropertyChanged("CutoffTime");
					this.OnCutoffTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Comment", DbType="NVarChar(200)")]
		public string Comment
		{
			get
			{
				return this._Comment;
			}
			set
			{
				if ((this._Comment != value))
				{
					this.OnCommentChanging(value);
					this.SendPropertyChanging();
					this._Comment = value;
					this.SendPropertyChanged("Comment");
					this.OnCommentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TimeTransition", DbType="DateTime")]
		public System.Nullable<System.DateTime> TimeTransition
		{
			get
			{
				return this._TimeTransition;
			}
			set
			{
				if ((this._TimeTransition != value))
				{
					this.OnTimeTransitionChanging(value);
					this.SendPropertyChanging();
					this._TimeTransition = value;
					this.SendPropertyChanged("TimeTransition");
					this.OnTimeTransitionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Created", DbType="DateTime")]
		public System.Nullable<System.DateTime> Created
		{
			get
			{
				return this._Created;
			}
			set
			{
				if ((this._Created != value))
				{
					this.OnCreatedChanging(value);
					this.SendPropertyChanging();
					this._Created = value;
					this.SendPropertyChanged("Created");
					this.OnCreatedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SortValue", DbType="Int")]
		public System.Nullable<int> SortValue
		{
			get
			{
				return this._SortValue;
			}
			set
			{
				if ((this._SortValue != value))
				{
					this.OnSortValueChanging(value);
					this.SendPropertyChanging();
					this._SortValue = value;
					this.SendPropertyChanged("SortValue");
					this.OnSortValueChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FlightType", DbType="VarChar(50)")]
		public string FlightType
		{
			get
			{
				return this._FlightType;
			}
			set
			{
				if ((this._FlightType != value))
				{
					this.OnFlightTypeChanging(value);
					this.SendPropertyChanging();
					this._FlightType = value;
					this.SendPropertyChanged("FlightType");
					this.OnFlightTypeChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.VCT")]
	public partial class VCT : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _LABS_IDENT_NO;
		
		private string _LABS_AWB;
		
		private System.Nullable<int> _LABS_QUANTITY_BOOKED;
		
		private System.Nullable<double> _LABS_WEIGHT_BOOKED;
		
		private string _AGENT_NAME;
		
		private string _BOOKING_FLIGHT;
		
		private System.Nullable<System.DateTime> _LABS_CREATED_AT;
		
		private string _LOADING;
		
		private System.Nullable<int> _AWB_STATUS;
		
		private string _LAST_GROUP;
		
		private System.Nullable<int> _LABS_EXPECT;
		
		private System.Nullable<int> _LABS_RECIEVED;
		
		private System.Nullable<int> _ISSUE_STATUS;
		
		private System.Nullable<int> _LOCATION;
		
		private System.Nullable<System.DateTime> _LABS_PROCESS_AT;
		
		private System.Nullable<int> _SortValue;
		
		private System.Nullable<System.DateTime> _CutOffTime;
		
		private string _CargoType;
		
		private System.Nullable<System.DateTime> _LABS_DIM_AT;
		
		private System.Nullable<System.DateTime> _VCT_DATE;
		
		private string _Note;
		
		private string _FlightID;
		
		private System.Nullable<int> _ConfirmStatus;
		
		private System.Nullable<System.DateTime> _LABS_CONFIRMED_AT;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnLABS_IDENT_NOChanging(string value);
    partial void OnLABS_IDENT_NOChanged();
    partial void OnLABS_AWBChanging(string value);
    partial void OnLABS_AWBChanged();
    partial void OnLABS_QUANTITY_BOOKEDChanging(System.Nullable<int> value);
    partial void OnLABS_QUANTITY_BOOKEDChanged();
    partial void OnLABS_WEIGHT_BOOKEDChanging(System.Nullable<double> value);
    partial void OnLABS_WEIGHT_BOOKEDChanged();
    partial void OnAGENT_NAMEChanging(string value);
    partial void OnAGENT_NAMEChanged();
    partial void OnBOOKING_FLIGHTChanging(string value);
    partial void OnBOOKING_FLIGHTChanged();
    partial void OnLABS_CREATED_ATChanging(System.Nullable<System.DateTime> value);
    partial void OnLABS_CREATED_ATChanged();
    partial void OnLOADINGChanging(string value);
    partial void OnLOADINGChanged();
    partial void OnAWB_STATUSChanging(System.Nullable<int> value);
    partial void OnAWB_STATUSChanged();
    partial void OnLAST_GROUPChanging(string value);
    partial void OnLAST_GROUPChanged();
    partial void OnLABS_EXPECTChanging(System.Nullable<int> value);
    partial void OnLABS_EXPECTChanged();
    partial void OnLABS_RECIEVEDChanging(System.Nullable<int> value);
    partial void OnLABS_RECIEVEDChanged();
    partial void OnISSUE_STATUSChanging(System.Nullable<int> value);
    partial void OnISSUE_STATUSChanged();
    partial void OnLOCATIONChanging(System.Nullable<int> value);
    partial void OnLOCATIONChanged();
    partial void OnLABS_PROCESS_ATChanging(System.Nullable<System.DateTime> value);
    partial void OnLABS_PROCESS_ATChanged();
    partial void OnSortValueChanging(System.Nullable<int> value);
    partial void OnSortValueChanged();
    partial void OnCutOffTimeChanging(System.Nullable<System.DateTime> value);
    partial void OnCutOffTimeChanged();
    partial void OnCargoTypeChanging(string value);
    partial void OnCargoTypeChanged();
    partial void OnLABS_DIM_ATChanging(System.Nullable<System.DateTime> value);
    partial void OnLABS_DIM_ATChanged();
    partial void OnVCT_DATEChanging(System.Nullable<System.DateTime> value);
    partial void OnVCT_DATEChanged();
    partial void OnNoteChanging(string value);
    partial void OnNoteChanged();
    partial void OnFlightIDChanging(string value);
    partial void OnFlightIDChanged();
    partial void OnConfirmStatusChanging(System.Nullable<int> value);
    partial void OnConfirmStatusChanged();
    partial void OnLABS_CONFIRMED_ATChanging(System.Nullable<System.DateTime> value);
    partial void OnLABS_CONFIRMED_ATChanged();
    #endregion
		
		public VCT()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LABS_IDENT_NO", DbType="VarChar(50)")]
		public string LABS_IDENT_NO
		{
			get
			{
				return this._LABS_IDENT_NO;
			}
			set
			{
				if ((this._LABS_IDENT_NO != value))
				{
					this.OnLABS_IDENT_NOChanging(value);
					this.SendPropertyChanging();
					this._LABS_IDENT_NO = value;
					this.SendPropertyChanged("LABS_IDENT_NO");
					this.OnLABS_IDENT_NOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LABS_AWB", DbType="VarChar(20)")]
		public string LABS_AWB
		{
			get
			{
				return this._LABS_AWB;
			}
			set
			{
				if ((this._LABS_AWB != value))
				{
					this.OnLABS_AWBChanging(value);
					this.SendPropertyChanging();
					this._LABS_AWB = value;
					this.SendPropertyChanged("LABS_AWB");
					this.OnLABS_AWBChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LABS_QUANTITY_BOOKED", DbType="Int")]
		public System.Nullable<int> LABS_QUANTITY_BOOKED
		{
			get
			{
				return this._LABS_QUANTITY_BOOKED;
			}
			set
			{
				if ((this._LABS_QUANTITY_BOOKED != value))
				{
					this.OnLABS_QUANTITY_BOOKEDChanging(value);
					this.SendPropertyChanging();
					this._LABS_QUANTITY_BOOKED = value;
					this.SendPropertyChanged("LABS_QUANTITY_BOOKED");
					this.OnLABS_QUANTITY_BOOKEDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LABS_WEIGHT_BOOKED", DbType="Float")]
		public System.Nullable<double> LABS_WEIGHT_BOOKED
		{
			get
			{
				return this._LABS_WEIGHT_BOOKED;
			}
			set
			{
				if ((this._LABS_WEIGHT_BOOKED != value))
				{
					this.OnLABS_WEIGHT_BOOKEDChanging(value);
					this.SendPropertyChanging();
					this._LABS_WEIGHT_BOOKED = value;
					this.SendPropertyChanged("LABS_WEIGHT_BOOKED");
					this.OnLABS_WEIGHT_BOOKEDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AGENT_NAME", DbType="NVarChar(500)")]
		public string AGENT_NAME
		{
			get
			{
				return this._AGENT_NAME;
			}
			set
			{
				if ((this._AGENT_NAME != value))
				{
					this.OnAGENT_NAMEChanging(value);
					this.SendPropertyChanging();
					this._AGENT_NAME = value;
					this.SendPropertyChanged("AGENT_NAME");
					this.OnAGENT_NAMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BOOKING_FLIGHT", DbType="VarChar(50)")]
		public string BOOKING_FLIGHT
		{
			get
			{
				return this._BOOKING_FLIGHT;
			}
			set
			{
				if ((this._BOOKING_FLIGHT != value))
				{
					this.OnBOOKING_FLIGHTChanging(value);
					this.SendPropertyChanging();
					this._BOOKING_FLIGHT = value;
					this.SendPropertyChanged("BOOKING_FLIGHT");
					this.OnBOOKING_FLIGHTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LABS_CREATED_AT", DbType="DateTime")]
		public System.Nullable<System.DateTime> LABS_CREATED_AT
		{
			get
			{
				return this._LABS_CREATED_AT;
			}
			set
			{
				if ((this._LABS_CREATED_AT != value))
				{
					this.OnLABS_CREATED_ATChanging(value);
					this.SendPropertyChanging();
					this._LABS_CREATED_AT = value;
					this.SendPropertyChanged("LABS_CREATED_AT");
					this.OnLABS_CREATED_ATChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LOADING", DbType="VarChar(50)")]
		public string LOADING
		{
			get
			{
				return this._LOADING;
			}
			set
			{
				if ((this._LOADING != value))
				{
					this.OnLOADINGChanging(value);
					this.SendPropertyChanging();
					this._LOADING = value;
					this.SendPropertyChanged("LOADING");
					this.OnLOADINGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AWB_STATUS", DbType="Int")]
		public System.Nullable<int> AWB_STATUS
		{
			get
			{
				return this._AWB_STATUS;
			}
			set
			{
				if ((this._AWB_STATUS != value))
				{
					this.OnAWB_STATUSChanging(value);
					this.SendPropertyChanging();
					this._AWB_STATUS = value;
					this.SendPropertyChanged("AWB_STATUS");
					this.OnAWB_STATUSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LAST_GROUP", DbType="VarChar(50)")]
		public string LAST_GROUP
		{
			get
			{
				return this._LAST_GROUP;
			}
			set
			{
				if ((this._LAST_GROUP != value))
				{
					this.OnLAST_GROUPChanging(value);
					this.SendPropertyChanging();
					this._LAST_GROUP = value;
					this.SendPropertyChanged("LAST_GROUP");
					this.OnLAST_GROUPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LABS_EXPECT", DbType="Int")]
		public System.Nullable<int> LABS_EXPECT
		{
			get
			{
				return this._LABS_EXPECT;
			}
			set
			{
				if ((this._LABS_EXPECT != value))
				{
					this.OnLABS_EXPECTChanging(value);
					this.SendPropertyChanging();
					this._LABS_EXPECT = value;
					this.SendPropertyChanged("LABS_EXPECT");
					this.OnLABS_EXPECTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LABS_RECIEVED", DbType="Int")]
		public System.Nullable<int> LABS_RECIEVED
		{
			get
			{
				return this._LABS_RECIEVED;
			}
			set
			{
				if ((this._LABS_RECIEVED != value))
				{
					this.OnLABS_RECIEVEDChanging(value);
					this.SendPropertyChanging();
					this._LABS_RECIEVED = value;
					this.SendPropertyChanged("LABS_RECIEVED");
					this.OnLABS_RECIEVEDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ISSUE_STATUS", DbType="Int")]
		public System.Nullable<int> ISSUE_STATUS
		{
			get
			{
				return this._ISSUE_STATUS;
			}
			set
			{
				if ((this._ISSUE_STATUS != value))
				{
					this.OnISSUE_STATUSChanging(value);
					this.SendPropertyChanging();
					this._ISSUE_STATUS = value;
					this.SendPropertyChanged("ISSUE_STATUS");
					this.OnISSUE_STATUSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LOCATION", DbType="Int")]
		public System.Nullable<int> LOCATION
		{
			get
			{
				return this._LOCATION;
			}
			set
			{
				if ((this._LOCATION != value))
				{
					this.OnLOCATIONChanging(value);
					this.SendPropertyChanging();
					this._LOCATION = value;
					this.SendPropertyChanged("LOCATION");
					this.OnLOCATIONChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LABS_PROCESS_AT", DbType="DateTime")]
		public System.Nullable<System.DateTime> LABS_PROCESS_AT
		{
			get
			{
				return this._LABS_PROCESS_AT;
			}
			set
			{
				if ((this._LABS_PROCESS_AT != value))
				{
					this.OnLABS_PROCESS_ATChanging(value);
					this.SendPropertyChanging();
					this._LABS_PROCESS_AT = value;
					this.SendPropertyChanged("LABS_PROCESS_AT");
					this.OnLABS_PROCESS_ATChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SortValue", DbType="Int")]
		public System.Nullable<int> SortValue
		{
			get
			{
				return this._SortValue;
			}
			set
			{
				if ((this._SortValue != value))
				{
					this.OnSortValueChanging(value);
					this.SendPropertyChanging();
					this._SortValue = value;
					this.SendPropertyChanged("SortValue");
					this.OnSortValueChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CutOffTime", DbType="DateTime")]
		public System.Nullable<System.DateTime> CutOffTime
		{
			get
			{
				return this._CutOffTime;
			}
			set
			{
				if ((this._CutOffTime != value))
				{
					this.OnCutOffTimeChanging(value);
					this.SendPropertyChanging();
					this._CutOffTime = value;
					this.SendPropertyChanged("CutOffTime");
					this.OnCutOffTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CargoType", DbType="VarChar(50)")]
		public string CargoType
		{
			get
			{
				return this._CargoType;
			}
			set
			{
				if ((this._CargoType != value))
				{
					this.OnCargoTypeChanging(value);
					this.SendPropertyChanging();
					this._CargoType = value;
					this.SendPropertyChanged("CargoType");
					this.OnCargoTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LABS_DIM_AT", DbType="DateTime")]
		public System.Nullable<System.DateTime> LABS_DIM_AT
		{
			get
			{
				return this._LABS_DIM_AT;
			}
			set
			{
				if ((this._LABS_DIM_AT != value))
				{
					this.OnLABS_DIM_ATChanging(value);
					this.SendPropertyChanging();
					this._LABS_DIM_AT = value;
					this.SendPropertyChanged("LABS_DIM_AT");
					this.OnLABS_DIM_ATChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VCT_DATE", DbType="Date")]
		public System.Nullable<System.DateTime> VCT_DATE
		{
			get
			{
				return this._VCT_DATE;
			}
			set
			{
				if ((this._VCT_DATE != value))
				{
					this.OnVCT_DATEChanging(value);
					this.SendPropertyChanging();
					this._VCT_DATE = value;
					this.SendPropertyChanged("VCT_DATE");
					this.OnVCT_DATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Note", DbType="NVarChar(100)")]
		public string Note
		{
			get
			{
				return this._Note;
			}
			set
			{
				if ((this._Note != value))
				{
					this.OnNoteChanging(value);
					this.SendPropertyChanging();
					this._Note = value;
					this.SendPropertyChanged("Note");
					this.OnNoteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FlightID", DbType="VarChar(50)")]
		public string FlightID
		{
			get
			{
				return this._FlightID;
			}
			set
			{
				if ((this._FlightID != value))
				{
					this.OnFlightIDChanging(value);
					this.SendPropertyChanging();
					this._FlightID = value;
					this.SendPropertyChanged("FlightID");
					this.OnFlightIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ConfirmStatus", DbType="Int")]
		public System.Nullable<int> ConfirmStatus
		{
			get
			{
				return this._ConfirmStatus;
			}
			set
			{
				if ((this._ConfirmStatus != value))
				{
					this.OnConfirmStatusChanging(value);
					this.SendPropertyChanging();
					this._ConfirmStatus = value;
					this.SendPropertyChanged("ConfirmStatus");
					this.OnConfirmStatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LABS_CONFIRMED_AT", DbType="DateTime")]
		public System.Nullable<System.DateTime> LABS_CONFIRMED_AT
		{
			get
			{
				return this._LABS_CONFIRMED_AT;
			}
			set
			{
				if ((this._LABS_CONFIRMED_AT != value))
				{
					this.OnLABS_CONFIRMED_ATChanging(value);
					this.SendPropertyChanging();
					this._LABS_CONFIRMED_AT = value;
					this.SendPropertyChanged("LABS_CONFIRMED_AT");
					this.OnLABS_CONFIRMED_ATChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.FLightFlup")]
	public partial class FLightFlup : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _FlightID;
		
		private System.Nullable<System.DateTime> _STD;
		
		private System.Nullable<System.DateTime> _ETD;
		
		private System.Nullable<System.DateTime> _LAT;
		
		private System.Nullable<System.DateTime> _Created;
		
		private string _FLightNumber;
		
		private string _FlightAirCraffType;
		
		private string _FlightType;
		
		private string _BookingFlight;
		
		private System.Nullable<int> _FinalLoad;
		
		private System.Nullable<System.DateTime> _FinishTime;
		
		private System.Nullable<int> _TotalULD;
		
		private System.Nullable<int> _RemainULD;
		
		private System.Nullable<int> _NeedPosition;
		
		private System.Nullable<int> _ManPower;
		
		private string _Remark;
		
		private System.Nullable<int> _TotalPosition;
		
		private System.Nullable<int> _FinishTimePerUld;
		
		private System.Nullable<int> _UldLoaded;
		
		private System.Nullable<int> _FlightStatus;
		
		private System.Nullable<int> _FlightDeleted;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnFlightIDChanging(string value);
    partial void OnFlightIDChanged();
    partial void OnSTDChanging(System.Nullable<System.DateTime> value);
    partial void OnSTDChanged();
    partial void OnETDChanging(System.Nullable<System.DateTime> value);
    partial void OnETDChanged();
    partial void OnLATChanging(System.Nullable<System.DateTime> value);
    partial void OnLATChanged();
    partial void OnCreatedChanging(System.Nullable<System.DateTime> value);
    partial void OnCreatedChanged();
    partial void OnFLightNumberChanging(string value);
    partial void OnFLightNumberChanged();
    partial void OnFlightAirCraffTypeChanging(string value);
    partial void OnFlightAirCraffTypeChanged();
    partial void OnFlightTypeChanging(string value);
    partial void OnFlightTypeChanged();
    partial void OnBookingFlightChanging(string value);
    partial void OnBookingFlightChanged();
    partial void OnFinalLoadChanging(System.Nullable<int> value);
    partial void OnFinalLoadChanged();
    partial void OnFinishTimeChanging(System.Nullable<System.DateTime> value);
    partial void OnFinishTimeChanged();
    partial void OnTotalULDChanging(System.Nullable<int> value);
    partial void OnTotalULDChanged();
    partial void OnRemainULDChanging(System.Nullable<int> value);
    partial void OnRemainULDChanged();
    partial void OnNeedPositionChanging(System.Nullable<int> value);
    partial void OnNeedPositionChanged();
    partial void OnManPowerChanging(System.Nullable<int> value);
    partial void OnManPowerChanged();
    partial void OnRemarkChanging(string value);
    partial void OnRemarkChanged();
    partial void OnTotalPositionChanging(System.Nullable<int> value);
    partial void OnTotalPositionChanged();
    partial void OnFinishTimePerUldChanging(System.Nullable<int> value);
    partial void OnFinishTimePerUldChanged();
    partial void OnUldLoadedChanging(System.Nullable<int> value);
    partial void OnUldLoadedChanged();
    partial void OnFlightStatusChanging(System.Nullable<int> value);
    partial void OnFlightStatusChanged();
    partial void OnFlightDeletedChanging(System.Nullable<int> value);
    partial void OnFlightDeletedChanged();
    #endregion
		
		public FLightFlup()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FlightID", DbType="VarChar(50)")]
		public string FlightID
		{
			get
			{
				return this._FlightID;
			}
			set
			{
				if ((this._FlightID != value))
				{
					this.OnFlightIDChanging(value);
					this.SendPropertyChanging();
					this._FlightID = value;
					this.SendPropertyChanged("FlightID");
					this.OnFlightIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STD", DbType="DateTime")]
		public System.Nullable<System.DateTime> STD
		{
			get
			{
				return this._STD;
			}
			set
			{
				if ((this._STD != value))
				{
					this.OnSTDChanging(value);
					this.SendPropertyChanging();
					this._STD = value;
					this.SendPropertyChanged("STD");
					this.OnSTDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ETD", DbType="DateTime")]
		public System.Nullable<System.DateTime> ETD
		{
			get
			{
				return this._ETD;
			}
			set
			{
				if ((this._ETD != value))
				{
					this.OnETDChanging(value);
					this.SendPropertyChanging();
					this._ETD = value;
					this.SendPropertyChanged("ETD");
					this.OnETDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LAT", DbType="DateTime")]
		public System.Nullable<System.DateTime> LAT
		{
			get
			{
				return this._LAT;
			}
			set
			{
				if ((this._LAT != value))
				{
					this.OnLATChanging(value);
					this.SendPropertyChanging();
					this._LAT = value;
					this.SendPropertyChanged("LAT");
					this.OnLATChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Created", DbType="DateTime")]
		public System.Nullable<System.DateTime> Created
		{
			get
			{
				return this._Created;
			}
			set
			{
				if ((this._Created != value))
				{
					this.OnCreatedChanging(value);
					this.SendPropertyChanging();
					this._Created = value;
					this.SendPropertyChanged("Created");
					this.OnCreatedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FLightNumber", DbType="VarChar(50)")]
		public string FLightNumber
		{
			get
			{
				return this._FLightNumber;
			}
			set
			{
				if ((this._FLightNumber != value))
				{
					this.OnFLightNumberChanging(value);
					this.SendPropertyChanging();
					this._FLightNumber = value;
					this.SendPropertyChanged("FLightNumber");
					this.OnFLightNumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FlightAirCraffType", DbType="VarChar(50)")]
		public string FlightAirCraffType
		{
			get
			{
				return this._FlightAirCraffType;
			}
			set
			{
				if ((this._FlightAirCraffType != value))
				{
					this.OnFlightAirCraffTypeChanging(value);
					this.SendPropertyChanging();
					this._FlightAirCraffType = value;
					this.SendPropertyChanged("FlightAirCraffType");
					this.OnFlightAirCraffTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FlightType", DbType="VarChar(50)")]
		public string FlightType
		{
			get
			{
				return this._FlightType;
			}
			set
			{
				if ((this._FlightType != value))
				{
					this.OnFlightTypeChanging(value);
					this.SendPropertyChanging();
					this._FlightType = value;
					this.SendPropertyChanged("FlightType");
					this.OnFlightTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BookingFlight", DbType="VarChar(50)")]
		public string BookingFlight
		{
			get
			{
				return this._BookingFlight;
			}
			set
			{
				if ((this._BookingFlight != value))
				{
					this.OnBookingFlightChanging(value);
					this.SendPropertyChanging();
					this._BookingFlight = value;
					this.SendPropertyChanged("BookingFlight");
					this.OnBookingFlightChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FinalLoad", DbType="Int")]
		public System.Nullable<int> FinalLoad
		{
			get
			{
				return this._FinalLoad;
			}
			set
			{
				if ((this._FinalLoad != value))
				{
					this.OnFinalLoadChanging(value);
					this.SendPropertyChanging();
					this._FinalLoad = value;
					this.SendPropertyChanged("FinalLoad");
					this.OnFinalLoadChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FinishTime", DbType="DateTime")]
		public System.Nullable<System.DateTime> FinishTime
		{
			get
			{
				return this._FinishTime;
			}
			set
			{
				if ((this._FinishTime != value))
				{
					this.OnFinishTimeChanging(value);
					this.SendPropertyChanging();
					this._FinishTime = value;
					this.SendPropertyChanged("FinishTime");
					this.OnFinishTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TotalULD", DbType="Int")]
		public System.Nullable<int> TotalULD
		{
			get
			{
				return this._TotalULD;
			}
			set
			{
				if ((this._TotalULD != value))
				{
					this.OnTotalULDChanging(value);
					this.SendPropertyChanging();
					this._TotalULD = value;
					this.SendPropertyChanged("TotalULD");
					this.OnTotalULDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RemainULD", DbType="Int")]
		public System.Nullable<int> RemainULD
		{
			get
			{
				return this._RemainULD;
			}
			set
			{
				if ((this._RemainULD != value))
				{
					this.OnRemainULDChanging(value);
					this.SendPropertyChanging();
					this._RemainULD = value;
					this.SendPropertyChanged("RemainULD");
					this.OnRemainULDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NeedPosition", DbType="Int")]
		public System.Nullable<int> NeedPosition
		{
			get
			{
				return this._NeedPosition;
			}
			set
			{
				if ((this._NeedPosition != value))
				{
					this.OnNeedPositionChanging(value);
					this.SendPropertyChanging();
					this._NeedPosition = value;
					this.SendPropertyChanged("NeedPosition");
					this.OnNeedPositionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ManPower", DbType="Int")]
		public System.Nullable<int> ManPower
		{
			get
			{
				return this._ManPower;
			}
			set
			{
				if ((this._ManPower != value))
				{
					this.OnManPowerChanging(value);
					this.SendPropertyChanging();
					this._ManPower = value;
					this.SendPropertyChanged("ManPower");
					this.OnManPowerChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Remark", DbType="NVarChar(250)")]
		public string Remark
		{
			get
			{
				return this._Remark;
			}
			set
			{
				if ((this._Remark != value))
				{
					this.OnRemarkChanging(value);
					this.SendPropertyChanging();
					this._Remark = value;
					this.SendPropertyChanged("Remark");
					this.OnRemarkChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TotalPosition", DbType="Int")]
		public System.Nullable<int> TotalPosition
		{
			get
			{
				return this._TotalPosition;
			}
			set
			{
				if ((this._TotalPosition != value))
				{
					this.OnTotalPositionChanging(value);
					this.SendPropertyChanging();
					this._TotalPosition = value;
					this.SendPropertyChanged("TotalPosition");
					this.OnTotalPositionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FinishTimePerUld", DbType="Int")]
		public System.Nullable<int> FinishTimePerUld
		{
			get
			{
				return this._FinishTimePerUld;
			}
			set
			{
				if ((this._FinishTimePerUld != value))
				{
					this.OnFinishTimePerUldChanging(value);
					this.SendPropertyChanging();
					this._FinishTimePerUld = value;
					this.SendPropertyChanged("FinishTimePerUld");
					this.OnFinishTimePerUldChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UldLoaded", DbType="Int")]
		public System.Nullable<int> UldLoaded
		{
			get
			{
				return this._UldLoaded;
			}
			set
			{
				if ((this._UldLoaded != value))
				{
					this.OnUldLoadedChanging(value);
					this.SendPropertyChanging();
					this._UldLoaded = value;
					this.SendPropertyChanged("UldLoaded");
					this.OnUldLoadedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FlightStatus", DbType="Int")]
		public System.Nullable<int> FlightStatus
		{
			get
			{
				return this._FlightStatus;
			}
			set
			{
				if ((this._FlightStatus != value))
				{
					this.OnFlightStatusChanging(value);
					this.SendPropertyChanging();
					this._FlightStatus = value;
					this.SendPropertyChanged("FlightStatus");
					this.OnFlightStatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FlightDeleted", DbType="Int")]
		public System.Nullable<int> FlightDeleted
		{
			get
			{
				return this._FlightDeleted;
			}
			set
			{
				if ((this._FlightDeleted != value))
				{
					this.OnFlightDeletedChanging(value);
					this.SendPropertyChanging();
					this._FlightDeleted = value;
					this.SendPropertyChanged("FlightDeleted");
					this.OnFlightDeletedChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
