#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TASK.DATA
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="ALSC_FLIGHTCONTROL")]
	public partial class FlightControlDbContextDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertULDAssignLog(ULDAssignLog instance);
    partial void UpdateULDAssignLog(ULDAssignLog instance);
    partial void DeleteULDAssignLog(ULDAssignLog instance);
    partial void InsertLocation(Location instance);
    partial void UpdateLocation(Location instance);
    partial void DeleteLocation(Location instance);
    partial void InsertULD_TYPE(ULD_TYPE instance);
    partial void UpdateULD_TYPE(ULD_TYPE instance);
    partial void DeleteULD_TYPE(ULD_TYPE instance);
    partial void InsertULDByFlight(ULDByFlight instance);
    partial void UpdateULDByFlight(ULDByFlight instance);
    partial void DeleteULDByFlight(ULDByFlight instance);
    partial void InsertFlight(Flight instance);
    partial void UpdateFlight(Flight instance);
    partial void DeleteFlight(Flight instance);
    partial void InsertSHCConfig(SHCConfig instance);
    partial void UpdateSHCConfig(SHCConfig instance);
    partial void DeleteSHCConfig(SHCConfig instance);
    partial void InsertAWBByULD(AWBByULD instance);
    partial void UpdateAWBByULD(AWBByULD instance);
    partial void DeleteAWBByULD(AWBByULD instance);
    partial void InsertHawbInAwb(HawbInAwb instance);
    partial void UpdateHawbInAwb(HawbInAwb instance);
    partial void DeleteHawbInAwb(HawbInAwb instance);
    partial void InsertFlightConfig(FlightConfig instance);
    partial void UpdateFlightConfig(FlightConfig instance);
    partial void DeleteFlightConfig(FlightConfig instance);
    #endregion
		
		public FlightControlDbContextDataContext() : 
				base(global::TASK.DATA.Properties.Settings.Default.ALSC_FLIGHTCONTROLConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public FlightControlDbContextDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public FlightControlDbContextDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public FlightControlDbContextDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public FlightControlDbContextDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<ULDAssignLog> ULDAssignLogs
		{
			get
			{
				return this.GetTable<ULDAssignLog>();
			}
		}
		
		public System.Data.Linq.Table<Location> Locations
		{
			get
			{
				return this.GetTable<Location>();
			}
		}
		
		public System.Data.Linq.Table<ULD_TYPE> ULD_TYPEs
		{
			get
			{
				return this.GetTable<ULD_TYPE>();
			}
		}
		
		public System.Data.Linq.Table<ULDByFlight> ULDByFlights
		{
			get
			{
				return this.GetTable<ULDByFlight>();
			}
		}
		
		public System.Data.Linq.Table<Flight> Flights
		{
			get
			{
				return this.GetTable<Flight>();
			}
		}
		
		public System.Data.Linq.Table<SHCConfig> SHCConfigs
		{
			get
			{
				return this.GetTable<SHCConfig>();
			}
		}
		
		public System.Data.Linq.Table<AWBByULD> AWBByULDs
		{
			get
			{
				return this.GetTable<AWBByULD>();
			}
		}
		
		public System.Data.Linq.Table<HawbInAwb> HawbInAwbs
		{
			get
			{
				return this.GetTable<HawbInAwb>();
			}
		}
		
		public System.Data.Linq.Table<FlightConfig> FlightConfigs
		{
			get
			{
				return this.GetTable<FlightConfig>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ULDAssignLog")]
	public partial class ULDAssignLog : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _ULD;
		
		private string _Location;
		
		private System.Nullable<System.DateTime> _Created;
		
		private System.Nullable<System.DateTime> _StartTime;
		
		private System.Nullable<System.DateTime> _FinishTime;
		
		private System.Nullable<bool> _Status;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnULDChanging(string value);
    partial void OnULDChanged();
    partial void OnLocationChanging(string value);
    partial void OnLocationChanged();
    partial void OnCreatedChanging(System.Nullable<System.DateTime> value);
    partial void OnCreatedChanged();
    partial void OnStartTimeChanging(System.Nullable<System.DateTime> value);
    partial void OnStartTimeChanged();
    partial void OnFinishTimeChanging(System.Nullable<System.DateTime> value);
    partial void OnFinishTimeChanged();
    partial void OnStatusChanging(System.Nullable<bool> value);
    partial void OnStatusChanged();
    #endregion
		
		public ULDAssignLog()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ULD", DbType="VarChar(50)")]
		public string ULD
		{
			get
			{
				return this._ULD;
			}
			set
			{
				if ((this._ULD != value))
				{
					this.OnULDChanging(value);
					this.SendPropertyChanging();
					this._ULD = value;
					this.SendPropertyChanged("ULD");
					this.OnULDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Location", DbType="VarChar(50)")]
		public string Location
		{
			get
			{
				return this._Location;
			}
			set
			{
				if ((this._Location != value))
				{
					this.OnLocationChanging(value);
					this.SendPropertyChanging();
					this._Location = value;
					this.SendPropertyChanged("Location");
					this.OnLocationChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Created", DbType="DateTime")]
		public System.Nullable<System.DateTime> Created
		{
			get
			{
				return this._Created;
			}
			set
			{
				if ((this._Created != value))
				{
					this.OnCreatedChanging(value);
					this.SendPropertyChanging();
					this._Created = value;
					this.SendPropertyChanged("Created");
					this.OnCreatedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StartTime", DbType="DateTime")]
		public System.Nullable<System.DateTime> StartTime
		{
			get
			{
				return this._StartTime;
			}
			set
			{
				if ((this._StartTime != value))
				{
					this.OnStartTimeChanging(value);
					this.SendPropertyChanging();
					this._StartTime = value;
					this.SendPropertyChanged("StartTime");
					this.OnStartTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FinishTime", DbType="DateTime")]
		public System.Nullable<System.DateTime> FinishTime
		{
			get
			{
				return this._FinishTime;
			}
			set
			{
				if ((this._FinishTime != value))
				{
					this.OnFinishTimeChanging(value);
					this.SendPropertyChanging();
					this._FinishTime = value;
					this.SendPropertyChanged("FinishTime");
					this.OnFinishTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Status", DbType="Bit")]
		public System.Nullable<bool> Status
		{
			get
			{
				return this._Status;
			}
			set
			{
				if ((this._Status != value))
				{
					this.OnStatusChanging(value);
					this.SendPropertyChanging();
					this._Status = value;
					this.SendPropertyChanged("Status");
					this.OnStatusChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Location")]
	public partial class Location : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _LocationName;
		
		private System.Nullable<bool> _Status;
		
		private int _LocationID;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnLocationNameChanging(string value);
    partial void OnLocationNameChanged();
    partial void OnStatusChanging(System.Nullable<bool> value);
    partial void OnStatusChanged();
    partial void OnLocationIDChanging(int value);
    partial void OnLocationIDChanged();
    #endregion
		
		public Location()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LocationName", DbType="VarChar(50)")]
		public string LocationName
		{
			get
			{
				return this._LocationName;
			}
			set
			{
				if ((this._LocationName != value))
				{
					this.OnLocationNameChanging(value);
					this.SendPropertyChanging();
					this._LocationName = value;
					this.SendPropertyChanged("LocationName");
					this.OnLocationNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Status", DbType="Bit")]
		public System.Nullable<bool> Status
		{
			get
			{
				return this._Status;
			}
			set
			{
				if ((this._Status != value))
				{
					this.OnStatusChanging(value);
					this.SendPropertyChanging();
					this._Status = value;
					this.SendPropertyChanged("Status");
					this.OnStatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LocationID", DbType="Int NOT NULL")]
		public int LocationID
		{
			get
			{
				return this._LocationID;
			}
			set
			{
				if ((this._LocationID != value))
				{
					this.OnLocationIDChanging(value);
					this.SendPropertyChanging();
					this._LocationID = value;
					this.SendPropertyChanged("LocationID");
					this.OnLocationIDChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ULD_TYPE")]
	public partial class ULD_TYPE : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _Name;
		
		private int _TimeOperation;
		
		private System.Nullable<int> _TimeNotify;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnNameChanging(string value);
    partial void OnNameChanged();
    partial void OnTimeOperationChanging(int value);
    partial void OnTimeOperationChanged();
    partial void OnTimeNotifyChanging(System.Nullable<int> value);
    partial void OnTimeNotifyChanged();
    #endregion
		
		public ULD_TYPE()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this.OnNameChanging(value);
					this.SendPropertyChanging();
					this._Name = value;
					this.SendPropertyChanged("Name");
					this.OnNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TimeOperation", DbType="Int NOT NULL")]
		public int TimeOperation
		{
			get
			{
				return this._TimeOperation;
			}
			set
			{
				if ((this._TimeOperation != value))
				{
					this.OnTimeOperationChanging(value);
					this.SendPropertyChanging();
					this._TimeOperation = value;
					this.SendPropertyChanged("TimeOperation");
					this.OnTimeOperationChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TimeNotify", DbType="Int")]
		public System.Nullable<int> TimeNotify
		{
			get
			{
				return this._TimeNotify;
			}
			set
			{
				if ((this._TimeNotify != value))
				{
					this.OnTimeNotifyChanging(value);
					this.SendPropertyChanging();
					this._TimeNotify = value;
					this.SendPropertyChanged("TimeNotify");
					this.OnTimeNotifyChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ULDByFlight")]
	public partial class ULDByFlight : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _Name;
		
		private System.Nullable<int> _Status;
		
		private System.Nullable<System.Guid> _Flight_ID;
		
		private string _FlightNumber;
		
		private System.Nullable<int> _ULD_TYPE;
		
		private System.Nullable<int> _LocationID;
		
		private string _Note;
		
		private System.Nullable<System.DateTime> _StartTime;
		
		private System.Nullable<System.DateTime> _FinishTime;
		
		private System.Nullable<bool> _Warning;
		
		private System.Nullable<int> _NotifyID;
		
		private string _NotifyMessage;
		
		private string _StatusMessage;
		
		private System.Nullable<int> _TimeToFinish;
		
		private System.Nullable<int> _Priority;
		
		private string _SHC;
		
		private System.Nullable<int> _CheckValue;
		
		private System.Nullable<System.Guid> _ULDID;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnNameChanging(string value);
    partial void OnNameChanged();
    partial void OnStatusChanging(System.Nullable<int> value);
    partial void OnStatusChanged();
    partial void OnFlight_IDChanging(System.Nullable<System.Guid> value);
    partial void OnFlight_IDChanged();
    partial void OnFlightNumberChanging(string value);
    partial void OnFlightNumberChanged();
    partial void OnULD_TYPEChanging(System.Nullable<int> value);
    partial void OnULD_TYPEChanged();
    partial void OnLocationIDChanging(System.Nullable<int> value);
    partial void OnLocationIDChanged();
    partial void OnNoteChanging(string value);
    partial void OnNoteChanged();
    partial void OnStartTimeChanging(System.Nullable<System.DateTime> value);
    partial void OnStartTimeChanged();
    partial void OnFinishTimeChanging(System.Nullable<System.DateTime> value);
    partial void OnFinishTimeChanged();
    partial void OnWarningChanging(System.Nullable<bool> value);
    partial void OnWarningChanged();
    partial void OnNotifyIDChanging(System.Nullable<int> value);
    partial void OnNotifyIDChanged();
    partial void OnNotifyMessageChanging(string value);
    partial void OnNotifyMessageChanged();
    partial void OnStatusMessageChanging(string value);
    partial void OnStatusMessageChanged();
    partial void OnTimeToFinishChanging(System.Nullable<int> value);
    partial void OnTimeToFinishChanged();
    partial void OnPriorityChanging(System.Nullable<int> value);
    partial void OnPriorityChanged();
    partial void OnSHCChanging(string value);
    partial void OnSHCChanged();
    partial void OnCheckValueChanging(System.Nullable<int> value);
    partial void OnCheckValueChanged();
    partial void OnULDIDChanging(System.Nullable<System.Guid> value);
    partial void OnULDIDChanged();
    #endregion
		
		public ULDByFlight()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="VarChar(50)")]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this.OnNameChanging(value);
					this.SendPropertyChanging();
					this._Name = value;
					this.SendPropertyChanged("Name");
					this.OnNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Status", DbType="Int")]
		public System.Nullable<int> Status
		{
			get
			{
				return this._Status;
			}
			set
			{
				if ((this._Status != value))
				{
					this.OnStatusChanging(value);
					this.SendPropertyChanging();
					this._Status = value;
					this.SendPropertyChanged("Status");
					this.OnStatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Flight_ID", DbType="UniqueIdentifier")]
		public System.Nullable<System.Guid> Flight_ID
		{
			get
			{
				return this._Flight_ID;
			}
			set
			{
				if ((this._Flight_ID != value))
				{
					this.OnFlight_IDChanging(value);
					this.SendPropertyChanging();
					this._Flight_ID = value;
					this.SendPropertyChanged("Flight_ID");
					this.OnFlight_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FlightNumber", DbType="VarChar(50)")]
		public string FlightNumber
		{
			get
			{
				return this._FlightNumber;
			}
			set
			{
				if ((this._FlightNumber != value))
				{
					this.OnFlightNumberChanging(value);
					this.SendPropertyChanging();
					this._FlightNumber = value;
					this.SendPropertyChanged("FlightNumber");
					this.OnFlightNumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ULD_TYPE", DbType="Int")]
		public System.Nullable<int> ULD_TYPE
		{
			get
			{
				return this._ULD_TYPE;
			}
			set
			{
				if ((this._ULD_TYPE != value))
				{
					this.OnULD_TYPEChanging(value);
					this.SendPropertyChanging();
					this._ULD_TYPE = value;
					this.SendPropertyChanged("ULD_TYPE");
					this.OnULD_TYPEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LocationID", DbType="Int")]
		public System.Nullable<int> LocationID
		{
			get
			{
				return this._LocationID;
			}
			set
			{
				if ((this._LocationID != value))
				{
					this.OnLocationIDChanging(value);
					this.SendPropertyChanging();
					this._LocationID = value;
					this.SendPropertyChanged("LocationID");
					this.OnLocationIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Note", DbType="NVarChar(500)")]
		public string Note
		{
			get
			{
				return this._Note;
			}
			set
			{
				if ((this._Note != value))
				{
					this.OnNoteChanging(value);
					this.SendPropertyChanging();
					this._Note = value;
					this.SendPropertyChanged("Note");
					this.OnNoteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StartTime", DbType="DateTime")]
		public System.Nullable<System.DateTime> StartTime
		{
			get
			{
				return this._StartTime;
			}
			set
			{
				if ((this._StartTime != value))
				{
					this.OnStartTimeChanging(value);
					this.SendPropertyChanging();
					this._StartTime = value;
					this.SendPropertyChanged("StartTime");
					this.OnStartTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FinishTime", DbType="DateTime")]
		public System.Nullable<System.DateTime> FinishTime
		{
			get
			{
				return this._FinishTime;
			}
			set
			{
				if ((this._FinishTime != value))
				{
					this.OnFinishTimeChanging(value);
					this.SendPropertyChanging();
					this._FinishTime = value;
					this.SendPropertyChanged("FinishTime");
					this.OnFinishTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Warning", DbType="Bit")]
		public System.Nullable<bool> Warning
		{
			get
			{
				return this._Warning;
			}
			set
			{
				if ((this._Warning != value))
				{
					this.OnWarningChanging(value);
					this.SendPropertyChanging();
					this._Warning = value;
					this.SendPropertyChanged("Warning");
					this.OnWarningChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NotifyID", DbType="Int")]
		public System.Nullable<int> NotifyID
		{
			get
			{
				return this._NotifyID;
			}
			set
			{
				if ((this._NotifyID != value))
				{
					this.OnNotifyIDChanging(value);
					this.SendPropertyChanging();
					this._NotifyID = value;
					this.SendPropertyChanged("NotifyID");
					this.OnNotifyIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NotifyMessage", DbType="NVarChar(50)")]
		public string NotifyMessage
		{
			get
			{
				return this._NotifyMessage;
			}
			set
			{
				if ((this._NotifyMessage != value))
				{
					this.OnNotifyMessageChanging(value);
					this.SendPropertyChanging();
					this._NotifyMessage = value;
					this.SendPropertyChanged("NotifyMessage");
					this.OnNotifyMessageChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StatusMessage", DbType="NVarChar(50)")]
		public string StatusMessage
		{
			get
			{
				return this._StatusMessage;
			}
			set
			{
				if ((this._StatusMessage != value))
				{
					this.OnStatusMessageChanging(value);
					this.SendPropertyChanging();
					this._StatusMessage = value;
					this.SendPropertyChanged("StatusMessage");
					this.OnStatusMessageChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TimeToFinish", DbType="Int")]
		public System.Nullable<int> TimeToFinish
		{
			get
			{
				return this._TimeToFinish;
			}
			set
			{
				if ((this._TimeToFinish != value))
				{
					this.OnTimeToFinishChanging(value);
					this.SendPropertyChanging();
					this._TimeToFinish = value;
					this.SendPropertyChanged("TimeToFinish");
					this.OnTimeToFinishChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Priority", DbType="Int")]
		public System.Nullable<int> Priority
		{
			get
			{
				return this._Priority;
			}
			set
			{
				if ((this._Priority != value))
				{
					this.OnPriorityChanging(value);
					this.SendPropertyChanging();
					this._Priority = value;
					this.SendPropertyChanged("Priority");
					this.OnPriorityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SHC", DbType="VarChar(500)")]
		public string SHC
		{
			get
			{
				return this._SHC;
			}
			set
			{
				if ((this._SHC != value))
				{
					this.OnSHCChanging(value);
					this.SendPropertyChanging();
					this._SHC = value;
					this.SendPropertyChanged("SHC");
					this.OnSHCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CheckValue", DbType="Int")]
		public System.Nullable<int> CheckValue
		{
			get
			{
				return this._CheckValue;
			}
			set
			{
				if ((this._CheckValue != value))
				{
					this.OnCheckValueChanging(value);
					this.SendPropertyChanging();
					this._CheckValue = value;
					this.SendPropertyChanged("CheckValue");
					this.OnCheckValueChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ULDID", DbType="UniqueIdentifier")]
		public System.Nullable<System.Guid> ULDID
		{
			get
			{
				return this._ULDID;
			}
			set
			{
				if ((this._ULDID != value))
				{
					this.OnULDIDChanging(value);
					this.SendPropertyChanging();
					this._ULDID = value;
					this.SendPropertyChanged("ULDID");
					this.OnULDIDChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Flight")]
	public partial class Flight : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private System.Guid _FlightID;
		
		private string _FlightNumber;
		
		private System.Nullable<System.DateTime> _Schedule;
		
		private System.Nullable<System.DateTime> _LandedDate;
		
		private System.Nullable<System.DateTime> _Created;
		
		private System.Nullable<bool> _Status;
		
		private System.Nullable<int> _FLUI_SCHEDULE_DATE;
		
		private System.Nullable<int> _FLUI_SCHEDULE_TIME;
		
		private System.Nullable<int> _FLUI_LANDED_DATE;
		
		private System.Nullable<int> _FLUI_LANDED_TIME;
		
		private string _FlightType;
		
		private string _FlightTypeOfAirCraft;
		
		private System.Nullable<int> _SOPTIME;
		
		private System.Nullable<int> _AlertTime1;
		
		private System.Nullable<int> _AlertTime2;
		
		private System.Nullable<int> _AlertTime3;
		
		private string _FlightLetter;
		
		private System.Nullable<System.DateTime> _FinishTime;
		
		private System.Nullable<int> _SHCTIME;
		
		private System.Nullable<int> _AlertSHC1;
		
		private System.Nullable<int> _AlertSHC2;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnFlightIDChanging(System.Guid value);
    partial void OnFlightIDChanged();
    partial void OnFlightNumberChanging(string value);
    partial void OnFlightNumberChanged();
    partial void OnScheduleChanging(System.Nullable<System.DateTime> value);
    partial void OnScheduleChanged();
    partial void OnLandedDateChanging(System.Nullable<System.DateTime> value);
    partial void OnLandedDateChanged();
    partial void OnCreatedChanging(System.Nullable<System.DateTime> value);
    partial void OnCreatedChanged();
    partial void OnStatusChanging(System.Nullable<bool> value);
    partial void OnStatusChanged();
    partial void OnFLUI_SCHEDULE_DATEChanging(System.Nullable<int> value);
    partial void OnFLUI_SCHEDULE_DATEChanged();
    partial void OnFLUI_SCHEDULE_TIMEChanging(System.Nullable<int> value);
    partial void OnFLUI_SCHEDULE_TIMEChanged();
    partial void OnFLUI_LANDED_DATEChanging(System.Nullable<int> value);
    partial void OnFLUI_LANDED_DATEChanged();
    partial void OnFLUI_LANDED_TIMEChanging(System.Nullable<int> value);
    partial void OnFLUI_LANDED_TIMEChanged();
    partial void OnFlightTypeChanging(string value);
    partial void OnFlightTypeChanged();
    partial void OnFlightTypeOfAirCraftChanging(string value);
    partial void OnFlightTypeOfAirCraftChanged();
    partial void OnSOPTIMEChanging(System.Nullable<int> value);
    partial void OnSOPTIMEChanged();
    partial void OnAlertTime1Changing(System.Nullable<int> value);
    partial void OnAlertTime1Changed();
    partial void OnAlertTime2Changing(System.Nullable<int> value);
    partial void OnAlertTime2Changed();
    partial void OnAlertTime3Changing(System.Nullable<int> value);
    partial void OnAlertTime3Changed();
    partial void OnFlightLetterChanging(string value);
    partial void OnFlightLetterChanged();
    partial void OnFinishTimeChanging(System.Nullable<System.DateTime> value);
    partial void OnFinishTimeChanged();
    partial void OnSHCTIMEChanging(System.Nullable<int> value);
    partial void OnSHCTIMEChanged();
    partial void OnAlertSHC1Changing(System.Nullable<int> value);
    partial void OnAlertSHC1Changed();
    partial void OnAlertSHC2Changing(System.Nullable<int> value);
    partial void OnAlertSHC2Changed();
    #endregion
		
		public Flight()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FlightID", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid FlightID
		{
			get
			{
				return this._FlightID;
			}
			set
			{
				if ((this._FlightID != value))
				{
					this.OnFlightIDChanging(value);
					this.SendPropertyChanging();
					this._FlightID = value;
					this.SendPropertyChanged("FlightID");
					this.OnFlightIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FlightNumber", DbType="VarChar(50)")]
		public string FlightNumber
		{
			get
			{
				return this._FlightNumber;
			}
			set
			{
				if ((this._FlightNumber != value))
				{
					this.OnFlightNumberChanging(value);
					this.SendPropertyChanging();
					this._FlightNumber = value;
					this.SendPropertyChanged("FlightNumber");
					this.OnFlightNumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Schedule", DbType="DateTime")]
		public System.Nullable<System.DateTime> Schedule
		{
			get
			{
				return this._Schedule;
			}
			set
			{
				if ((this._Schedule != value))
				{
					this.OnScheduleChanging(value);
					this.SendPropertyChanging();
					this._Schedule = value;
					this.SendPropertyChanged("Schedule");
					this.OnScheduleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LandedDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> LandedDate
		{
			get
			{
				return this._LandedDate;
			}
			set
			{
				if ((this._LandedDate != value))
				{
					this.OnLandedDateChanging(value);
					this.SendPropertyChanging();
					this._LandedDate = value;
					this.SendPropertyChanged("LandedDate");
					this.OnLandedDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Created", DbType="DateTime")]
		public System.Nullable<System.DateTime> Created
		{
			get
			{
				return this._Created;
			}
			set
			{
				if ((this._Created != value))
				{
					this.OnCreatedChanging(value);
					this.SendPropertyChanging();
					this._Created = value;
					this.SendPropertyChanged("Created");
					this.OnCreatedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Status", DbType="Bit")]
		public System.Nullable<bool> Status
		{
			get
			{
				return this._Status;
			}
			set
			{
				if ((this._Status != value))
				{
					this.OnStatusChanging(value);
					this.SendPropertyChanging();
					this._Status = value;
					this.SendPropertyChanged("Status");
					this.OnStatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FLUI_SCHEDULE_DATE", DbType="Int")]
		public System.Nullable<int> FLUI_SCHEDULE_DATE
		{
			get
			{
				return this._FLUI_SCHEDULE_DATE;
			}
			set
			{
				if ((this._FLUI_SCHEDULE_DATE != value))
				{
					this.OnFLUI_SCHEDULE_DATEChanging(value);
					this.SendPropertyChanging();
					this._FLUI_SCHEDULE_DATE = value;
					this.SendPropertyChanged("FLUI_SCHEDULE_DATE");
					this.OnFLUI_SCHEDULE_DATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FLUI_SCHEDULE_TIME", DbType="Int")]
		public System.Nullable<int> FLUI_SCHEDULE_TIME
		{
			get
			{
				return this._FLUI_SCHEDULE_TIME;
			}
			set
			{
				if ((this._FLUI_SCHEDULE_TIME != value))
				{
					this.OnFLUI_SCHEDULE_TIMEChanging(value);
					this.SendPropertyChanging();
					this._FLUI_SCHEDULE_TIME = value;
					this.SendPropertyChanged("FLUI_SCHEDULE_TIME");
					this.OnFLUI_SCHEDULE_TIMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FLUI_LANDED_DATE", DbType="Int")]
		public System.Nullable<int> FLUI_LANDED_DATE
		{
			get
			{
				return this._FLUI_LANDED_DATE;
			}
			set
			{
				if ((this._FLUI_LANDED_DATE != value))
				{
					this.OnFLUI_LANDED_DATEChanging(value);
					this.SendPropertyChanging();
					this._FLUI_LANDED_DATE = value;
					this.SendPropertyChanged("FLUI_LANDED_DATE");
					this.OnFLUI_LANDED_DATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FLUI_LANDED_TIME", DbType="Int")]
		public System.Nullable<int> FLUI_LANDED_TIME
		{
			get
			{
				return this._FLUI_LANDED_TIME;
			}
			set
			{
				if ((this._FLUI_LANDED_TIME != value))
				{
					this.OnFLUI_LANDED_TIMEChanging(value);
					this.SendPropertyChanging();
					this._FLUI_LANDED_TIME = value;
					this.SendPropertyChanged("FLUI_LANDED_TIME");
					this.OnFLUI_LANDED_TIMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FlightType", DbType="VarChar(50)")]
		public string FlightType
		{
			get
			{
				return this._FlightType;
			}
			set
			{
				if ((this._FlightType != value))
				{
					this.OnFlightTypeChanging(value);
					this.SendPropertyChanging();
					this._FlightType = value;
					this.SendPropertyChanged("FlightType");
					this.OnFlightTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FlightTypeOfAirCraft", DbType="VarChar(50)")]
		public string FlightTypeOfAirCraft
		{
			get
			{
				return this._FlightTypeOfAirCraft;
			}
			set
			{
				if ((this._FlightTypeOfAirCraft != value))
				{
					this.OnFlightTypeOfAirCraftChanging(value);
					this.SendPropertyChanging();
					this._FlightTypeOfAirCraft = value;
					this.SendPropertyChanged("FlightTypeOfAirCraft");
					this.OnFlightTypeOfAirCraftChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SOPTIME", DbType="Int")]
		public System.Nullable<int> SOPTIME
		{
			get
			{
				return this._SOPTIME;
			}
			set
			{
				if ((this._SOPTIME != value))
				{
					this.OnSOPTIMEChanging(value);
					this.SendPropertyChanging();
					this._SOPTIME = value;
					this.SendPropertyChanged("SOPTIME");
					this.OnSOPTIMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AlertTime1", DbType="Int")]
		public System.Nullable<int> AlertTime1
		{
			get
			{
				return this._AlertTime1;
			}
			set
			{
				if ((this._AlertTime1 != value))
				{
					this.OnAlertTime1Changing(value);
					this.SendPropertyChanging();
					this._AlertTime1 = value;
					this.SendPropertyChanged("AlertTime1");
					this.OnAlertTime1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AlertTime2", DbType="Int")]
		public System.Nullable<int> AlertTime2
		{
			get
			{
				return this._AlertTime2;
			}
			set
			{
				if ((this._AlertTime2 != value))
				{
					this.OnAlertTime2Changing(value);
					this.SendPropertyChanging();
					this._AlertTime2 = value;
					this.SendPropertyChanged("AlertTime2");
					this.OnAlertTime2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AlertTime3", DbType="Int")]
		public System.Nullable<int> AlertTime3
		{
			get
			{
				return this._AlertTime3;
			}
			set
			{
				if ((this._AlertTime3 != value))
				{
					this.OnAlertTime3Changing(value);
					this.SendPropertyChanging();
					this._AlertTime3 = value;
					this.SendPropertyChanged("AlertTime3");
					this.OnAlertTime3Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FlightLetter", DbType="VarChar(50)")]
		public string FlightLetter
		{
			get
			{
				return this._FlightLetter;
			}
			set
			{
				if ((this._FlightLetter != value))
				{
					this.OnFlightLetterChanging(value);
					this.SendPropertyChanging();
					this._FlightLetter = value;
					this.SendPropertyChanged("FlightLetter");
					this.OnFlightLetterChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FinishTime", DbType="DateTime")]
		public System.Nullable<System.DateTime> FinishTime
		{
			get
			{
				return this._FinishTime;
			}
			set
			{
				if ((this._FinishTime != value))
				{
					this.OnFinishTimeChanging(value);
					this.SendPropertyChanging();
					this._FinishTime = value;
					this.SendPropertyChanged("FinishTime");
					this.OnFinishTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SHCTIME", DbType="Int")]
		public System.Nullable<int> SHCTIME
		{
			get
			{
				return this._SHCTIME;
			}
			set
			{
				if ((this._SHCTIME != value))
				{
					this.OnSHCTIMEChanging(value);
					this.SendPropertyChanging();
					this._SHCTIME = value;
					this.SendPropertyChanged("SHCTIME");
					this.OnSHCTIMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AlertSHC1", DbType="Int")]
		public System.Nullable<int> AlertSHC1
		{
			get
			{
				return this._AlertSHC1;
			}
			set
			{
				if ((this._AlertSHC1 != value))
				{
					this.OnAlertSHC1Changing(value);
					this.SendPropertyChanging();
					this._AlertSHC1 = value;
					this.SendPropertyChanged("AlertSHC1");
					this.OnAlertSHC1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AlertSHC2", DbType="Int")]
		public System.Nullable<int> AlertSHC2
		{
			get
			{
				return this._AlertSHC2;
			}
			set
			{
				if ((this._AlertSHC2 != value))
				{
					this.OnAlertSHC2Changing(value);
					this.SendPropertyChanging();
					this._AlertSHC2 = value;
					this.SendPropertyChanged("AlertSHC2");
					this.OnAlertSHC2Changed();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.SHCConfig")]
	public partial class SHCConfig : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _Code;
		
		private string _Location;
		
		private string _Description;
		
		private System.Nullable<int> _Priority;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnCodeChanging(string value);
    partial void OnCodeChanged();
    partial void OnLocationChanging(string value);
    partial void OnLocationChanged();
    partial void OnDescriptionChanging(string value);
    partial void OnDescriptionChanged();
    partial void OnPriorityChanging(System.Nullable<int> value);
    partial void OnPriorityChanged();
    #endregion
		
		public SHCConfig()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Code", DbType="VarChar(50)")]
		public string Code
		{
			get
			{
				return this._Code;
			}
			set
			{
				if ((this._Code != value))
				{
					this.OnCodeChanging(value);
					this.SendPropertyChanging();
					this._Code = value;
					this.SendPropertyChanged("Code");
					this.OnCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Location", DbType="VarChar(50)")]
		public string Location
		{
			get
			{
				return this._Location;
			}
			set
			{
				if ((this._Location != value))
				{
					this.OnLocationChanging(value);
					this.SendPropertyChanging();
					this._Location = value;
					this.SendPropertyChanged("Location");
					this.OnLocationChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Description", DbType="NVarChar(100)")]
		public string Description
		{
			get
			{
				return this._Description;
			}
			set
			{
				if ((this._Description != value))
				{
					this.OnDescriptionChanging(value);
					this.SendPropertyChanging();
					this._Description = value;
					this.SendPropertyChanged("Description");
					this.OnDescriptionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Priority", DbType="Int")]
		public System.Nullable<int> Priority
		{
			get
			{
				return this._Priority;
			}
			set
			{
				if ((this._Priority != value))
				{
					this.OnPriorityChanging(value);
					this.SendPropertyChanging();
					this._Priority = value;
					this.SendPropertyChanged("Priority");
					this.OnPriorityChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.AWBByULD")]
	public partial class AWBByULD : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private System.Nullable<System.Guid> _ULD_ID;
		
		private System.Nullable<System.Guid> _Flight_ID;
		
		private string _AWB;
		
		private string _SHC;
		
		private System.Nullable<int> _CheckValue;
		
		private System.Nullable<int> _Process;
		
		private System.Nullable<int> _Lagi_Identity;
		
		private System.Nullable<System.DateTime> _TimeFinish;
		
		private System.Nullable<System.Guid> _AWB_ID;
		
		private System.Nullable<bool> _HaveMultiHawb;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnULD_IDChanging(System.Nullable<System.Guid> value);
    partial void OnULD_IDChanged();
    partial void OnFlight_IDChanging(System.Nullable<System.Guid> value);
    partial void OnFlight_IDChanged();
    partial void OnAWBChanging(string value);
    partial void OnAWBChanged();
    partial void OnSHCChanging(string value);
    partial void OnSHCChanged();
    partial void OnCheckValueChanging(System.Nullable<int> value);
    partial void OnCheckValueChanged();
    partial void OnProcessChanging(System.Nullable<int> value);
    partial void OnProcessChanged();
    partial void OnLagi_IdentityChanging(System.Nullable<int> value);
    partial void OnLagi_IdentityChanged();
    partial void OnTimeFinishChanging(System.Nullable<System.DateTime> value);
    partial void OnTimeFinishChanged();
    partial void OnAWB_IDChanging(System.Nullable<System.Guid> value);
    partial void OnAWB_IDChanged();
    partial void OnHaveMultiHawbChanging(System.Nullable<bool> value);
    partial void OnHaveMultiHawbChanged();
    #endregion
		
		public AWBByULD()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ULD_ID", DbType="UniqueIdentifier")]
		public System.Nullable<System.Guid> ULD_ID
		{
			get
			{
				return this._ULD_ID;
			}
			set
			{
				if ((this._ULD_ID != value))
				{
					this.OnULD_IDChanging(value);
					this.SendPropertyChanging();
					this._ULD_ID = value;
					this.SendPropertyChanged("ULD_ID");
					this.OnULD_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Flight_ID", DbType="UniqueIdentifier")]
		public System.Nullable<System.Guid> Flight_ID
		{
			get
			{
				return this._Flight_ID;
			}
			set
			{
				if ((this._Flight_ID != value))
				{
					this.OnFlight_IDChanging(value);
					this.SendPropertyChanging();
					this._Flight_ID = value;
					this.SendPropertyChanged("Flight_ID");
					this.OnFlight_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AWB", DbType="VarChar(50)")]
		public string AWB
		{
			get
			{
				return this._AWB;
			}
			set
			{
				if ((this._AWB != value))
				{
					this.OnAWBChanging(value);
					this.SendPropertyChanging();
					this._AWB = value;
					this.SendPropertyChanged("AWB");
					this.OnAWBChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SHC", DbType="VarChar(500)")]
		public string SHC
		{
			get
			{
				return this._SHC;
			}
			set
			{
				if ((this._SHC != value))
				{
					this.OnSHCChanging(value);
					this.SendPropertyChanging();
					this._SHC = value;
					this.SendPropertyChanged("SHC");
					this.OnSHCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CheckValue", DbType="Int")]
		public System.Nullable<int> CheckValue
		{
			get
			{
				return this._CheckValue;
			}
			set
			{
				if ((this._CheckValue != value))
				{
					this.OnCheckValueChanging(value);
					this.SendPropertyChanging();
					this._CheckValue = value;
					this.SendPropertyChanged("CheckValue");
					this.OnCheckValueChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Process", DbType="Int")]
		public System.Nullable<int> Process
		{
			get
			{
				return this._Process;
			}
			set
			{
				if ((this._Process != value))
				{
					this.OnProcessChanging(value);
					this.SendPropertyChanging();
					this._Process = value;
					this.SendPropertyChanged("Process");
					this.OnProcessChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Lagi_Identity", DbType="Int")]
		public System.Nullable<int> Lagi_Identity
		{
			get
			{
				return this._Lagi_Identity;
			}
			set
			{
				if ((this._Lagi_Identity != value))
				{
					this.OnLagi_IdentityChanging(value);
					this.SendPropertyChanging();
					this._Lagi_Identity = value;
					this.SendPropertyChanged("Lagi_Identity");
					this.OnLagi_IdentityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TimeFinish", DbType="DateTime")]
		public System.Nullable<System.DateTime> TimeFinish
		{
			get
			{
				return this._TimeFinish;
			}
			set
			{
				if ((this._TimeFinish != value))
				{
					this.OnTimeFinishChanging(value);
					this.SendPropertyChanging();
					this._TimeFinish = value;
					this.SendPropertyChanged("TimeFinish");
					this.OnTimeFinishChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AWB_ID", DbType="UniqueIdentifier")]
		public System.Nullable<System.Guid> AWB_ID
		{
			get
			{
				return this._AWB_ID;
			}
			set
			{
				if ((this._AWB_ID != value))
				{
					this.OnAWB_IDChanging(value);
					this.SendPropertyChanging();
					this._AWB_ID = value;
					this.SendPropertyChanged("AWB_ID");
					this.OnAWB_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HaveMultiHawb", DbType="Bit")]
		public System.Nullable<bool> HaveMultiHawb
		{
			get
			{
				return this._HaveMultiHawb;
			}
			set
			{
				if ((this._HaveMultiHawb != value))
				{
					this.OnHaveMultiHawbChanging(value);
					this.SendPropertyChanging();
					this._HaveMultiHawb = value;
					this.SendPropertyChanged("HaveMultiHawb");
					this.OnHaveMultiHawbChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.HawbInAwb")]
	public partial class HawbInAwb : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private System.Nullable<System.Guid> _FlightID;
		
		private System.Nullable<System.Guid> _AWB_ID;
		
		private string _HAWB;
		
		private System.Nullable<int> _CheckValue;
		
		private System.Nullable<int> _Process;
		
		private System.Nullable<System.DateTime> _TimeFinish;
		
		private System.Nullable<bool> _Bql;
		
		private System.Nullable<int> _Lagi_Identity;
		
		private System.Nullable<bool> _Fast;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnFlightIDChanging(System.Nullable<System.Guid> value);
    partial void OnFlightIDChanged();
    partial void OnAWB_IDChanging(System.Nullable<System.Guid> value);
    partial void OnAWB_IDChanged();
    partial void OnHAWBChanging(string value);
    partial void OnHAWBChanged();
    partial void OnCheckValueChanging(System.Nullable<int> value);
    partial void OnCheckValueChanged();
    partial void OnProcessChanging(System.Nullable<int> value);
    partial void OnProcessChanged();
    partial void OnTimeFinishChanging(System.Nullable<System.DateTime> value);
    partial void OnTimeFinishChanged();
    partial void OnBqlChanging(System.Nullable<bool> value);
    partial void OnBqlChanged();
    partial void OnLagi_IdentityChanging(System.Nullable<int> value);
    partial void OnLagi_IdentityChanged();
    partial void OnFastChanging(System.Nullable<bool> value);
    partial void OnFastChanged();
    #endregion
		
		public HawbInAwb()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FlightID", DbType="UniqueIdentifier")]
		public System.Nullable<System.Guid> FlightID
		{
			get
			{
				return this._FlightID;
			}
			set
			{
				if ((this._FlightID != value))
				{
					this.OnFlightIDChanging(value);
					this.SendPropertyChanging();
					this._FlightID = value;
					this.SendPropertyChanged("FlightID");
					this.OnFlightIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AWB_ID", DbType="UniqueIdentifier")]
		public System.Nullable<System.Guid> AWB_ID
		{
			get
			{
				return this._AWB_ID;
			}
			set
			{
				if ((this._AWB_ID != value))
				{
					this.OnAWB_IDChanging(value);
					this.SendPropertyChanging();
					this._AWB_ID = value;
					this.SendPropertyChanged("AWB_ID");
					this.OnAWB_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HAWB", DbType="VarChar(50)")]
		public string HAWB
		{
			get
			{
				return this._HAWB;
			}
			set
			{
				if ((this._HAWB != value))
				{
					this.OnHAWBChanging(value);
					this.SendPropertyChanging();
					this._HAWB = value;
					this.SendPropertyChanged("HAWB");
					this.OnHAWBChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CheckValue", DbType="Int")]
		public System.Nullable<int> CheckValue
		{
			get
			{
				return this._CheckValue;
			}
			set
			{
				if ((this._CheckValue != value))
				{
					this.OnCheckValueChanging(value);
					this.SendPropertyChanging();
					this._CheckValue = value;
					this.SendPropertyChanged("CheckValue");
					this.OnCheckValueChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Process", DbType="Int")]
		public System.Nullable<int> Process
		{
			get
			{
				return this._Process;
			}
			set
			{
				if ((this._Process != value))
				{
					this.OnProcessChanging(value);
					this.SendPropertyChanging();
					this._Process = value;
					this.SendPropertyChanged("Process");
					this.OnProcessChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TimeFinish", DbType="DateTime")]
		public System.Nullable<System.DateTime> TimeFinish
		{
			get
			{
				return this._TimeFinish;
			}
			set
			{
				if ((this._TimeFinish != value))
				{
					this.OnTimeFinishChanging(value);
					this.SendPropertyChanging();
					this._TimeFinish = value;
					this.SendPropertyChanged("TimeFinish");
					this.OnTimeFinishChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Bql", DbType="Bit")]
		public System.Nullable<bool> Bql
		{
			get
			{
				return this._Bql;
			}
			set
			{
				if ((this._Bql != value))
				{
					this.OnBqlChanging(value);
					this.SendPropertyChanging();
					this._Bql = value;
					this.SendPropertyChanged("Bql");
					this.OnBqlChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Lagi_Identity", DbType="Int")]
		public System.Nullable<int> Lagi_Identity
		{
			get
			{
				return this._Lagi_Identity;
			}
			set
			{
				if ((this._Lagi_Identity != value))
				{
					this.OnLagi_IdentityChanging(value);
					this.SendPropertyChanging();
					this._Lagi_Identity = value;
					this.SendPropertyChanged("Lagi_Identity");
					this.OnLagi_IdentityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fast", DbType="Bit")]
		public System.Nullable<bool> Fast
		{
			get
			{
				return this._Fast;
			}
			set
			{
				if ((this._Fast != value))
				{
					this.OnFastChanging(value);
					this.SendPropertyChanging();
					this._Fast = value;
					this.SendPropertyChanged("Fast");
					this.OnFastChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.FlightConfig")]
	public partial class FlightConfig : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _FlightNumber;
		
		private string _FlightType;
		
		private string _FlightTypeOfAirCraft;
		
		private System.Nullable<int> _SopTime;
		
		private System.Nullable<int> _AlertTime1;
		
		private System.Nullable<int> _AlertTime2;
		
		private System.Nullable<int> _AlertTime3;
		
		private System.Nullable<int> _SHCTIME;
		
		private System.Nullable<int> _AlertSHC1;
		
		private System.Nullable<int> _AlertSHC2;
		
		private System.Nullable<int> _FinalLoad;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnFlightNumberChanging(string value);
    partial void OnFlightNumberChanged();
    partial void OnFlightTypeChanging(string value);
    partial void OnFlightTypeChanged();
    partial void OnFlightTypeOfAirCraftChanging(string value);
    partial void OnFlightTypeOfAirCraftChanged();
    partial void OnSopTimeChanging(System.Nullable<int> value);
    partial void OnSopTimeChanged();
    partial void OnAlertTime1Changing(System.Nullable<int> value);
    partial void OnAlertTime1Changed();
    partial void OnAlertTime2Changing(System.Nullable<int> value);
    partial void OnAlertTime2Changed();
    partial void OnAlertTime3Changing(System.Nullable<int> value);
    partial void OnAlertTime3Changed();
    partial void OnSHCTIMEChanging(System.Nullable<int> value);
    partial void OnSHCTIMEChanged();
    partial void OnAlertSHC1Changing(System.Nullable<int> value);
    partial void OnAlertSHC1Changed();
    partial void OnAlertSHC2Changing(System.Nullable<int> value);
    partial void OnAlertSHC2Changed();
    partial void OnFinalLoadChanging(System.Nullable<int> value);
    partial void OnFinalLoadChanged();
    #endregion
		
		public FlightConfig()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FlightNumber", DbType="VarChar(50)")]
		public string FlightNumber
		{
			get
			{
				return this._FlightNumber;
			}
			set
			{
				if ((this._FlightNumber != value))
				{
					this.OnFlightNumberChanging(value);
					this.SendPropertyChanging();
					this._FlightNumber = value;
					this.SendPropertyChanged("FlightNumber");
					this.OnFlightNumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FlightType", DbType="VarChar(50)")]
		public string FlightType
		{
			get
			{
				return this._FlightType;
			}
			set
			{
				if ((this._FlightType != value))
				{
					this.OnFlightTypeChanging(value);
					this.SendPropertyChanging();
					this._FlightType = value;
					this.SendPropertyChanged("FlightType");
					this.OnFlightTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FlightTypeOfAirCraft", DbType="VarChar(50)")]
		public string FlightTypeOfAirCraft
		{
			get
			{
				return this._FlightTypeOfAirCraft;
			}
			set
			{
				if ((this._FlightTypeOfAirCraft != value))
				{
					this.OnFlightTypeOfAirCraftChanging(value);
					this.SendPropertyChanging();
					this._FlightTypeOfAirCraft = value;
					this.SendPropertyChanged("FlightTypeOfAirCraft");
					this.OnFlightTypeOfAirCraftChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SopTime", DbType="Int")]
		public System.Nullable<int> SopTime
		{
			get
			{
				return this._SopTime;
			}
			set
			{
				if ((this._SopTime != value))
				{
					this.OnSopTimeChanging(value);
					this.SendPropertyChanging();
					this._SopTime = value;
					this.SendPropertyChanged("SopTime");
					this.OnSopTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AlertTime1", DbType="Int")]
		public System.Nullable<int> AlertTime1
		{
			get
			{
				return this._AlertTime1;
			}
			set
			{
				if ((this._AlertTime1 != value))
				{
					this.OnAlertTime1Changing(value);
					this.SendPropertyChanging();
					this._AlertTime1 = value;
					this.SendPropertyChanged("AlertTime1");
					this.OnAlertTime1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AlertTime2", DbType="Int")]
		public System.Nullable<int> AlertTime2
		{
			get
			{
				return this._AlertTime2;
			}
			set
			{
				if ((this._AlertTime2 != value))
				{
					this.OnAlertTime2Changing(value);
					this.SendPropertyChanging();
					this._AlertTime2 = value;
					this.SendPropertyChanged("AlertTime2");
					this.OnAlertTime2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AlertTime3", DbType="Int")]
		public System.Nullable<int> AlertTime3
		{
			get
			{
				return this._AlertTime3;
			}
			set
			{
				if ((this._AlertTime3 != value))
				{
					this.OnAlertTime3Changing(value);
					this.SendPropertyChanging();
					this._AlertTime3 = value;
					this.SendPropertyChanged("AlertTime3");
					this.OnAlertTime3Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SHCTIME", DbType="Int")]
		public System.Nullable<int> SHCTIME
		{
			get
			{
				return this._SHCTIME;
			}
			set
			{
				if ((this._SHCTIME != value))
				{
					this.OnSHCTIMEChanging(value);
					this.SendPropertyChanging();
					this._SHCTIME = value;
					this.SendPropertyChanged("SHCTIME");
					this.OnSHCTIMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AlertSHC1", DbType="Int")]
		public System.Nullable<int> AlertSHC1
		{
			get
			{
				return this._AlertSHC1;
			}
			set
			{
				if ((this._AlertSHC1 != value))
				{
					this.OnAlertSHC1Changing(value);
					this.SendPropertyChanging();
					this._AlertSHC1 = value;
					this.SendPropertyChanged("AlertSHC1");
					this.OnAlertSHC1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AlertSHC2", DbType="Int")]
		public System.Nullable<int> AlertSHC2
		{
			get
			{
				return this._AlertSHC2;
			}
			set
			{
				if ((this._AlertSHC2 != value))
				{
					this.OnAlertSHC2Changing(value);
					this.SendPropertyChanging();
					this._AlertSHC2 = value;
					this.SendPropertyChanged("AlertSHC2");
					this.OnAlertSHC2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FinalLoad", DbType="Int")]
		public System.Nullable<int> FinalLoad
		{
			get
			{
				return this._FinalLoad;
			}
			set
			{
				if ((this._FinalLoad != value))
				{
					this.OnFinalLoadChanging(value);
					this.SendPropertyChanging();
					this._FinalLoad = value;
					this.SendPropertyChanged("FinalLoad");
					this.OnFinalLoadChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
