#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TASK.DATA
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="QMSTickets")]
	public partial class LogCapSoDbDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertLogCapSo(LogCapSo instance);
    partial void UpdateLogCapSo(LogCapSo instance);
    partial void DeleteLogCapSo(LogCapSo instance);
    #endregion
		
		public LogCapSoDbDataContext() : 
				base(global::TASK.DATA.Properties.Settings.Default.QMSTicketsConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public LogCapSoDbDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public LogCapSoDbDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public LogCapSoDbDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public LogCapSoDbDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<LogCapSo> LogCapSos
		{
			get
			{
				return this.GetTable<LogCapSo>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.LogCapSo")]
	public partial class LogCapSo : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _QNO;
		
		private string _MAWB;
		
		private string _HAWB;
		
		private string _SPECIAL;
		
		private string _FLIGHT;
		
		private string _FLIGHTDATE;
		
		private System.Nullable<System.DateTime> _Created;
		
		private System.Nullable<int> _AWBRemain;
		
		private int _ID;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnQNOChanging(string value);
    partial void OnQNOChanged();
    partial void OnMAWBChanging(string value);
    partial void OnMAWBChanged();
    partial void OnHAWBChanging(string value);
    partial void OnHAWBChanged();
    partial void OnSPECIALChanging(string value);
    partial void OnSPECIALChanged();
    partial void OnFLIGHTChanging(string value);
    partial void OnFLIGHTChanged();
    partial void OnFLIGHTDATEChanging(string value);
    partial void OnFLIGHTDATEChanged();
    partial void OnCreatedChanging(System.Nullable<System.DateTime> value);
    partial void OnCreatedChanged();
    partial void OnAWBRemainChanging(System.Nullable<int> value);
    partial void OnAWBRemainChanged();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    #endregion
		
		public LogCapSo()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_QNO", DbType="VarChar(50)")]
		public string QNO
		{
			get
			{
				return this._QNO;
			}
			set
			{
				if ((this._QNO != value))
				{
					this.OnQNOChanging(value);
					this.SendPropertyChanging();
					this._QNO = value;
					this.SendPropertyChanged("QNO");
					this.OnQNOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAWB", DbType="VarChar(50)")]
		public string MAWB
		{
			get
			{
				return this._MAWB;
			}
			set
			{
				if ((this._MAWB != value))
				{
					this.OnMAWBChanging(value);
					this.SendPropertyChanging();
					this._MAWB = value;
					this.SendPropertyChanged("MAWB");
					this.OnMAWBChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HAWB", DbType="VarChar(20)")]
		public string HAWB
		{
			get
			{
				return this._HAWB;
			}
			set
			{
				if ((this._HAWB != value))
				{
					this.OnHAWBChanging(value);
					this.SendPropertyChanging();
					this._HAWB = value;
					this.SendPropertyChanged("HAWB");
					this.OnHAWBChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SPECIAL", DbType="VarChar(50)")]
		public string SPECIAL
		{
			get
			{
				return this._SPECIAL;
			}
			set
			{
				if ((this._SPECIAL != value))
				{
					this.OnSPECIALChanging(value);
					this.SendPropertyChanging();
					this._SPECIAL = value;
					this.SendPropertyChanged("SPECIAL");
					this.OnSPECIALChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FLIGHT", DbType="VarChar(20)")]
		public string FLIGHT
		{
			get
			{
				return this._FLIGHT;
			}
			set
			{
				if ((this._FLIGHT != value))
				{
					this.OnFLIGHTChanging(value);
					this.SendPropertyChanging();
					this._FLIGHT = value;
					this.SendPropertyChanged("FLIGHT");
					this.OnFLIGHTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FLIGHTDATE", DbType="VarChar(20)")]
		public string FLIGHTDATE
		{
			get
			{
				return this._FLIGHTDATE;
			}
			set
			{
				if ((this._FLIGHTDATE != value))
				{
					this.OnFLIGHTDATEChanging(value);
					this.SendPropertyChanging();
					this._FLIGHTDATE = value;
					this.SendPropertyChanged("FLIGHTDATE");
					this.OnFLIGHTDATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Created", DbType="DateTime")]
		public System.Nullable<System.DateTime> Created
		{
			get
			{
				return this._Created;
			}
			set
			{
				if ((this._Created != value))
				{
					this.OnCreatedChanging(value);
					this.SendPropertyChanging();
					this._Created = value;
					this.SendPropertyChanged("Created");
					this.OnCreatedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AWBRemain", DbType="Int")]
		public System.Nullable<int> AWBRemain
		{
			get
			{
				return this._AWBRemain;
			}
			set
			{
				if ((this._AWBRemain != value))
				{
					this.OnAWBRemainChanging(value);
					this.SendPropertyChanging();
					this._AWBRemain = value;
					this.SendPropertyChanged("AWBRemain");
					this.OnAWBRemainChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
