<?xml version="1.0" encoding="utf-8"?><Database Name="DBSPM.ALSNOIBAI" Class="PXKControlDbContextDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=10.10.1.10;Initial Catalog=DBSPM.ALSNOIBAI;Persist Security Info=True;User ID=sa" SettingsObjectName="TASK.DATA.Properties.Settings" SettingsPropertyName="DBSPM_ALSNOIBAIConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.tblPXK" Member="tblPXKs">
    <Type Name="tblPXK">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="PXK" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Created" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Status" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="VCT" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="AWB" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Hawb" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Pieces" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Weight" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="SOP" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Finish" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Note" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="UserName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="GroupNumer" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tblDangKyVaoRa" Member="tblDangKyVaoRas">
    <Type Name="tblDangKyVaoRa">
      <Column Name="ID" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="NgayGioVao" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="TicketID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TicketName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="TicketType" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="HoVaTen" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="CMND" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="DienThoai" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="DiaChi" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="BienSoXe" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="LoaiXe" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="LoaiVe" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TrongTai" Type="System.String" DbType="NChar(250)" CanBeNull="true" />
      <Column Name="GiaTien" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CongTy" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="PhongBan" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="NguoiLienHe" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="DienThoaiNguoiLienHe" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="CompanyID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CompanyName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="DepartmentID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DepartmentName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="MucDichCongViec" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="AnhCMNDPath" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="AnhKhuonMatPath" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="GhiChu" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="NguoiDangKyVao" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="NguoiXacNhanVao" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="TrangThai" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NgayGioRa" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="KetQuaKiemTraRa" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="NguoiKiemTraRa" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="IsSync" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="SyncID" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Floor" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NgayGioVaoThuc" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.LocationConfig" Member="LocationConfigs">
    <Type Name="LocationConfig">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Floor" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TotalSpace" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ThresholdPoint" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tblTicketStatus" Member="tblTicketStatus">
    <Type Name="tblTicketStatus">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TicketUID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="TicketCreatedAt" Type="System.DateTime" DbType="DateTime2" CanBeNull="true" />
      <Column Name="ActionCode" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ActionValue" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ActionDateTime" Type="System.DateTime" DbType="DateTime2 NOT NULL" CanBeNull="false" />
      <Column Name="BienSoXe" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ActionStatus" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ActionMessage" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="QrScan" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="TicketType" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.CallTruck" Member="CallTrucks">
    <Type Name="CallTruck">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="BSX" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Location" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Floor" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Created" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Note" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Remark" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="SortValue" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="VCT" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="SpaceEmptyFloor1" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SpaceEmptyFloor2" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Dock" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="TimeCalled" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tblDangKyGoiXe" Member="tblDangKyGoiXes">
    <Type Name="tblDangKyGoiXe">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="BienSoXe" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="TrongTai" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="LoHang" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="LoaiHang" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TenLaiXe" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="SoCMND" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ViTri" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TrangThai" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ThoiGianDangKy" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ThoiGianVao" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ThoiGianRa" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="GhiChu" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="DienThoai" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="QueryStatus" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="CallTruck" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Remark" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="SortValue" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="UserName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Note" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="GioGoi" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="SynID" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="TruckStatus" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
</Database>