#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TASK.DATA
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="DBSPM.ALSNOIBAI")]
	public partial class PXKControlDbContextDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InserttblPXK(tblPXK instance);
    partial void UpdatetblPXK(tblPXK instance);
    partial void DeletetblPXK(tblPXK instance);
    partial void InserttblDangKyVaoRa(tblDangKyVaoRa instance);
    partial void UpdatetblDangKyVaoRa(tblDangKyVaoRa instance);
    partial void DeletetblDangKyVaoRa(tblDangKyVaoRa instance);
    partial void InsertLocationConfig(LocationConfig instance);
    partial void UpdateLocationConfig(LocationConfig instance);
    partial void DeleteLocationConfig(LocationConfig instance);
    partial void InserttblTicketStatus(tblTicketStatus instance);
    partial void UpdatetblTicketStatus(tblTicketStatus instance);
    partial void DeletetblTicketStatus(tblTicketStatus instance);
    partial void InsertCallTruck(CallTruck instance);
    partial void UpdateCallTruck(CallTruck instance);
    partial void DeleteCallTruck(CallTruck instance);
    partial void InserttblDangKyGoiXe(tblDangKyGoiXe instance);
    partial void UpdatetblDangKyGoiXe(tblDangKyGoiXe instance);
    partial void DeletetblDangKyGoiXe(tblDangKyGoiXe instance);
    #endregion
		
		public PXKControlDbContextDataContext() : 
				base(global::TASK.DATA.Properties.Settings.Default.DBSPM_ALSNOIBAIConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public PXKControlDbContextDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public PXKControlDbContextDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public PXKControlDbContextDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public PXKControlDbContextDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<tblPXK> tblPXKs
		{
			get
			{
				return this.GetTable<tblPXK>();
			}
		}
		
		public System.Data.Linq.Table<tblDangKyVaoRa> tblDangKyVaoRas
		{
			get
			{
				return this.GetTable<tblDangKyVaoRa>();
			}
		}
		
		public System.Data.Linq.Table<LocationConfig> LocationConfigs
		{
			get
			{
				return this.GetTable<LocationConfig>();
			}
		}
		
		public System.Data.Linq.Table<tblTicketStatus> tblTicketStatus
		{
			get
			{
				return this.GetTable<tblTicketStatus>();
			}
		}
		
		public System.Data.Linq.Table<CallTruck> CallTrucks
		{
			get
			{
				return this.GetTable<CallTruck>();
			}
		}
		
		public System.Data.Linq.Table<tblDangKyGoiXe> tblDangKyGoiXes
		{
			get
			{
				return this.GetTable<tblDangKyGoiXe>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblPXK")]
	public partial class tblPXK : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _PXK;
		
		private System.Nullable<System.DateTime> _Created;
		
		private System.Nullable<int> _Status;
		
		private string _VCT;
		
		private string _AWB;
		
		private string _Hawb;
		
		private System.Nullable<double> _Pieces;
		
		private System.Nullable<double> _Weight;
		
		private System.Nullable<System.DateTime> _SOP;
		
		private System.Nullable<System.DateTime> _Finish;
		
		private string _Note;
		
		private string _UserName;
		
		private System.Nullable<int> _GroupNumer;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnPXKChanging(string value);
    partial void OnPXKChanged();
    partial void OnCreatedChanging(System.Nullable<System.DateTime> value);
    partial void OnCreatedChanged();
    partial void OnStatusChanging(System.Nullable<int> value);
    partial void OnStatusChanged();
    partial void OnVCTChanging(string value);
    partial void OnVCTChanged();
    partial void OnAWBChanging(string value);
    partial void OnAWBChanged();
    partial void OnHawbChanging(string value);
    partial void OnHawbChanged();
    partial void OnPiecesChanging(System.Nullable<double> value);
    partial void OnPiecesChanged();
    partial void OnWeightChanging(System.Nullable<double> value);
    partial void OnWeightChanged();
    partial void OnSOPChanging(System.Nullable<System.DateTime> value);
    partial void OnSOPChanged();
    partial void OnFinishChanging(System.Nullable<System.DateTime> value);
    partial void OnFinishChanged();
    partial void OnNoteChanging(string value);
    partial void OnNoteChanged();
    partial void OnUserNameChanging(string value);
    partial void OnUserNameChanged();
    partial void OnGroupNumerChanging(System.Nullable<int> value);
    partial void OnGroupNumerChanged();
    #endregion
		
		public tblPXK()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PXK", DbType="VarChar(50)")]
		public string PXK
		{
			get
			{
				return this._PXK;
			}
			set
			{
				if ((this._PXK != value))
				{
					this.OnPXKChanging(value);
					this.SendPropertyChanging();
					this._PXK = value;
					this.SendPropertyChanged("PXK");
					this.OnPXKChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Created", DbType="DateTime")]
		public System.Nullable<System.DateTime> Created
		{
			get
			{
				return this._Created;
			}
			set
			{
				if ((this._Created != value))
				{
					this.OnCreatedChanging(value);
					this.SendPropertyChanging();
					this._Created = value;
					this.SendPropertyChanged("Created");
					this.OnCreatedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Status", DbType="Int")]
		public System.Nullable<int> Status
		{
			get
			{
				return this._Status;
			}
			set
			{
				if ((this._Status != value))
				{
					this.OnStatusChanging(value);
					this.SendPropertyChanging();
					this._Status = value;
					this.SendPropertyChanged("Status");
					this.OnStatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VCT", DbType="VarChar(50)")]
		public string VCT
		{
			get
			{
				return this._VCT;
			}
			set
			{
				if ((this._VCT != value))
				{
					this.OnVCTChanging(value);
					this.SendPropertyChanging();
					this._VCT = value;
					this.SendPropertyChanged("VCT");
					this.OnVCTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AWB", DbType="VarChar(50)")]
		public string AWB
		{
			get
			{
				return this._AWB;
			}
			set
			{
				if ((this._AWB != value))
				{
					this.OnAWBChanging(value);
					this.SendPropertyChanging();
					this._AWB = value;
					this.SendPropertyChanged("AWB");
					this.OnAWBChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Hawb", DbType="VarChar(50)")]
		public string Hawb
		{
			get
			{
				return this._Hawb;
			}
			set
			{
				if ((this._Hawb != value))
				{
					this.OnHawbChanging(value);
					this.SendPropertyChanging();
					this._Hawb = value;
					this.SendPropertyChanged("Hawb");
					this.OnHawbChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Pieces", DbType="Float")]
		public System.Nullable<double> Pieces
		{
			get
			{
				return this._Pieces;
			}
			set
			{
				if ((this._Pieces != value))
				{
					this.OnPiecesChanging(value);
					this.SendPropertyChanging();
					this._Pieces = value;
					this.SendPropertyChanged("Pieces");
					this.OnPiecesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Weight", DbType="Float")]
		public System.Nullable<double> Weight
		{
			get
			{
				return this._Weight;
			}
			set
			{
				if ((this._Weight != value))
				{
					this.OnWeightChanging(value);
					this.SendPropertyChanging();
					this._Weight = value;
					this.SendPropertyChanged("Weight");
					this.OnWeightChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SOP", DbType="DateTime")]
		public System.Nullable<System.DateTime> SOP
		{
			get
			{
				return this._SOP;
			}
			set
			{
				if ((this._SOP != value))
				{
					this.OnSOPChanging(value);
					this.SendPropertyChanging();
					this._SOP = value;
					this.SendPropertyChanged("SOP");
					this.OnSOPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Finish", DbType="DateTime")]
		public System.Nullable<System.DateTime> Finish
		{
			get
			{
				return this._Finish;
			}
			set
			{
				if ((this._Finish != value))
				{
					this.OnFinishChanging(value);
					this.SendPropertyChanging();
					this._Finish = value;
					this.SendPropertyChanged("Finish");
					this.OnFinishChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Note", DbType="NVarChar(200)")]
		public string Note
		{
			get
			{
				return this._Note;
			}
			set
			{
				if ((this._Note != value))
				{
					this.OnNoteChanging(value);
					this.SendPropertyChanging();
					this._Note = value;
					this.SendPropertyChanged("Note");
					this.OnNoteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserName", DbType="VarChar(50)")]
		public string UserName
		{
			get
			{
				return this._UserName;
			}
			set
			{
				if ((this._UserName != value))
				{
					this.OnUserNameChanging(value);
					this.SendPropertyChanging();
					this._UserName = value;
					this.SendPropertyChanged("UserName");
					this.OnUserNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GroupNumer", DbType="Int")]
		public System.Nullable<int> GroupNumer
		{
			get
			{
				return this._GroupNumer;
			}
			set
			{
				if ((this._GroupNumer != value))
				{
					this.OnGroupNumerChanging(value);
					this.SendPropertyChanging();
					this._GroupNumer = value;
					this.SendPropertyChanged("GroupNumer");
					this.OnGroupNumerChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblDangKyVaoRa")]
	public partial class tblDangKyVaoRa : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _ID;
		
		private System.Nullable<System.DateTime> _NgayGioVao;
		
		private System.Nullable<int> _TicketID;
		
		private string _TicketName;
		
		private System.Nullable<int> _TicketType;
		
		private string _HoVaTen;
		
		private string _CMND;
		
		private string _DienThoai;
		
		private string _DiaChi;
		
		private string _BienSoXe;
		
		private System.Nullable<int> _LoaiXe;
		
		private System.Nullable<int> _LoaiVe;
		
		private string _TrongTai;
		
		private System.Nullable<int> _GiaTien;
		
		private string _CongTy;
		
		private string _PhongBan;
		
		private string _NguoiLienHe;
		
		private string _DienThoaiNguoiLienHe;
		
		private System.Nullable<int> _CompanyID;
		
		private string _CompanyName;
		
		private System.Nullable<int> _DepartmentID;
		
		private string _DepartmentName;
		
		private string _MucDichCongViec;
		
		private string _AnhCMNDPath;
		
		private string _AnhKhuonMatPath;
		
		private string _GhiChu;
		
		private string _NguoiDangKyVao;
		
		private string _NguoiXacNhanVao;
		
		private System.Nullable<int> _TrangThai;
		
		private System.Nullable<System.DateTime> _NgayGioRa;
		
		private string _KetQuaKiemTraRa;
		
		private string _NguoiKiemTraRa;
		
		private System.Nullable<bool> _IsSync;
		
		private string _SyncID;
		
		private System.Nullable<int> _Floor;
		
		private System.Nullable<System.DateTime> _NgayGioVaoThuc;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(long value);
    partial void OnIDChanged();
    partial void OnNgayGioVaoChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayGioVaoChanged();
    partial void OnTicketIDChanging(System.Nullable<int> value);
    partial void OnTicketIDChanged();
    partial void OnTicketNameChanging(string value);
    partial void OnTicketNameChanged();
    partial void OnTicketTypeChanging(System.Nullable<int> value);
    partial void OnTicketTypeChanged();
    partial void OnHoVaTenChanging(string value);
    partial void OnHoVaTenChanged();
    partial void OnCMNDChanging(string value);
    partial void OnCMNDChanged();
    partial void OnDienThoaiChanging(string value);
    partial void OnDienThoaiChanged();
    partial void OnDiaChiChanging(string value);
    partial void OnDiaChiChanged();
    partial void OnBienSoXeChanging(string value);
    partial void OnBienSoXeChanged();
    partial void OnLoaiXeChanging(System.Nullable<int> value);
    partial void OnLoaiXeChanged();
    partial void OnLoaiVeChanging(System.Nullable<int> value);
    partial void OnLoaiVeChanged();
    partial void OnTrongTaiChanging(string value);
    partial void OnTrongTaiChanged();
    partial void OnGiaTienChanging(System.Nullable<int> value);
    partial void OnGiaTienChanged();
    partial void OnCongTyChanging(string value);
    partial void OnCongTyChanged();
    partial void OnPhongBanChanging(string value);
    partial void OnPhongBanChanged();
    partial void OnNguoiLienHeChanging(string value);
    partial void OnNguoiLienHeChanged();
    partial void OnDienThoaiNguoiLienHeChanging(string value);
    partial void OnDienThoaiNguoiLienHeChanged();
    partial void OnCompanyIDChanging(System.Nullable<int> value);
    partial void OnCompanyIDChanged();
    partial void OnCompanyNameChanging(string value);
    partial void OnCompanyNameChanged();
    partial void OnDepartmentIDChanging(System.Nullable<int> value);
    partial void OnDepartmentIDChanged();
    partial void OnDepartmentNameChanging(string value);
    partial void OnDepartmentNameChanged();
    partial void OnMucDichCongViecChanging(string value);
    partial void OnMucDichCongViecChanged();
    partial void OnAnhCMNDPathChanging(string value);
    partial void OnAnhCMNDPathChanged();
    partial void OnAnhKhuonMatPathChanging(string value);
    partial void OnAnhKhuonMatPathChanged();
    partial void OnGhiChuChanging(string value);
    partial void OnGhiChuChanged();
    partial void OnNguoiDangKyVaoChanging(string value);
    partial void OnNguoiDangKyVaoChanged();
    partial void OnNguoiXacNhanVaoChanging(string value);
    partial void OnNguoiXacNhanVaoChanged();
    partial void OnTrangThaiChanging(System.Nullable<int> value);
    partial void OnTrangThaiChanged();
    partial void OnNgayGioRaChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayGioRaChanged();
    partial void OnKetQuaKiemTraRaChanging(string value);
    partial void OnKetQuaKiemTraRaChanged();
    partial void OnNguoiKiemTraRaChanging(string value);
    partial void OnNguoiKiemTraRaChanged();
    partial void OnIsSyncChanging(System.Nullable<bool> value);
    partial void OnIsSyncChanged();
    partial void OnSyncIDChanging(string value);
    partial void OnSyncIDChanged();
    partial void OnFloorChanging(System.Nullable<int> value);
    partial void OnFloorChanged();
    partial void OnNgayGioVaoThucChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayGioVaoThucChanged();
    #endregion
		
		public tblDangKyVaoRa()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayGioVao", DbType="DateTime")]
		public System.Nullable<System.DateTime> NgayGioVao
		{
			get
			{
				return this._NgayGioVao;
			}
			set
			{
				if ((this._NgayGioVao != value))
				{
					this.OnNgayGioVaoChanging(value);
					this.SendPropertyChanging();
					this._NgayGioVao = value;
					this.SendPropertyChanged("NgayGioVao");
					this.OnNgayGioVaoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TicketID", DbType="Int")]
		public System.Nullable<int> TicketID
		{
			get
			{
				return this._TicketID;
			}
			set
			{
				if ((this._TicketID != value))
				{
					this.OnTicketIDChanging(value);
					this.SendPropertyChanging();
					this._TicketID = value;
					this.SendPropertyChanged("TicketID");
					this.OnTicketIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TicketName", DbType="NVarChar(50)")]
		public string TicketName
		{
			get
			{
				return this._TicketName;
			}
			set
			{
				if ((this._TicketName != value))
				{
					this.OnTicketNameChanging(value);
					this.SendPropertyChanging();
					this._TicketName = value;
					this.SendPropertyChanged("TicketName");
					this.OnTicketNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TicketType", DbType="Int")]
		public System.Nullable<int> TicketType
		{
			get
			{
				return this._TicketType;
			}
			set
			{
				if ((this._TicketType != value))
				{
					this.OnTicketTypeChanging(value);
					this.SendPropertyChanging();
					this._TicketType = value;
					this.SendPropertyChanged("TicketType");
					this.OnTicketTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HoVaTen", DbType="NVarChar(50)")]
		public string HoVaTen
		{
			get
			{
				return this._HoVaTen;
			}
			set
			{
				if ((this._HoVaTen != value))
				{
					this.OnHoVaTenChanging(value);
					this.SendPropertyChanging();
					this._HoVaTen = value;
					this.SendPropertyChanged("HoVaTen");
					this.OnHoVaTenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CMND", DbType="NVarChar(50)")]
		public string CMND
		{
			get
			{
				return this._CMND;
			}
			set
			{
				if ((this._CMND != value))
				{
					this.OnCMNDChanging(value);
					this.SendPropertyChanging();
					this._CMND = value;
					this.SendPropertyChanged("CMND");
					this.OnCMNDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DienThoai", DbType="NVarChar(50)")]
		public string DienThoai
		{
			get
			{
				return this._DienThoai;
			}
			set
			{
				if ((this._DienThoai != value))
				{
					this.OnDienThoaiChanging(value);
					this.SendPropertyChanging();
					this._DienThoai = value;
					this.SendPropertyChanged("DienThoai");
					this.OnDienThoaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiaChi", DbType="NVarChar(500)")]
		public string DiaChi
		{
			get
			{
				return this._DiaChi;
			}
			set
			{
				if ((this._DiaChi != value))
				{
					this.OnDiaChiChanging(value);
					this.SendPropertyChanging();
					this._DiaChi = value;
					this.SendPropertyChanged("DiaChi");
					this.OnDiaChiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BienSoXe", DbType="NVarChar(50)")]
		public string BienSoXe
		{
			get
			{
				return this._BienSoXe;
			}
			set
			{
				if ((this._BienSoXe != value))
				{
					this.OnBienSoXeChanging(value);
					this.SendPropertyChanging();
					this._BienSoXe = value;
					this.SendPropertyChanged("BienSoXe");
					this.OnBienSoXeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LoaiXe", DbType="Int")]
		public System.Nullable<int> LoaiXe
		{
			get
			{
				return this._LoaiXe;
			}
			set
			{
				if ((this._LoaiXe != value))
				{
					this.OnLoaiXeChanging(value);
					this.SendPropertyChanging();
					this._LoaiXe = value;
					this.SendPropertyChanged("LoaiXe");
					this.OnLoaiXeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LoaiVe", DbType="Int")]
		public System.Nullable<int> LoaiVe
		{
			get
			{
				return this._LoaiVe;
			}
			set
			{
				if ((this._LoaiVe != value))
				{
					this.OnLoaiVeChanging(value);
					this.SendPropertyChanging();
					this._LoaiVe = value;
					this.SendPropertyChanged("LoaiVe");
					this.OnLoaiVeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TrongTai", DbType="NChar(250)")]
		public string TrongTai
		{
			get
			{
				return this._TrongTai;
			}
			set
			{
				if ((this._TrongTai != value))
				{
					this.OnTrongTaiChanging(value);
					this.SendPropertyChanging();
					this._TrongTai = value;
					this.SendPropertyChanged("TrongTai");
					this.OnTrongTaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GiaTien", DbType="Int")]
		public System.Nullable<int> GiaTien
		{
			get
			{
				return this._GiaTien;
			}
			set
			{
				if ((this._GiaTien != value))
				{
					this.OnGiaTienChanging(value);
					this.SendPropertyChanging();
					this._GiaTien = value;
					this.SendPropertyChanged("GiaTien");
					this.OnGiaTienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CongTy", DbType="NVarChar(50)")]
		public string CongTy
		{
			get
			{
				return this._CongTy;
			}
			set
			{
				if ((this._CongTy != value))
				{
					this.OnCongTyChanging(value);
					this.SendPropertyChanging();
					this._CongTy = value;
					this.SendPropertyChanged("CongTy");
					this.OnCongTyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PhongBan", DbType="NVarChar(50)")]
		public string PhongBan
		{
			get
			{
				return this._PhongBan;
			}
			set
			{
				if ((this._PhongBan != value))
				{
					this.OnPhongBanChanging(value);
					this.SendPropertyChanging();
					this._PhongBan = value;
					this.SendPropertyChanged("PhongBan");
					this.OnPhongBanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NguoiLienHe", DbType="NVarChar(50)")]
		public string NguoiLienHe
		{
			get
			{
				return this._NguoiLienHe;
			}
			set
			{
				if ((this._NguoiLienHe != value))
				{
					this.OnNguoiLienHeChanging(value);
					this.SendPropertyChanging();
					this._NguoiLienHe = value;
					this.SendPropertyChanged("NguoiLienHe");
					this.OnNguoiLienHeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DienThoaiNguoiLienHe", DbType="NVarChar(50)")]
		public string DienThoaiNguoiLienHe
		{
			get
			{
				return this._DienThoaiNguoiLienHe;
			}
			set
			{
				if ((this._DienThoaiNguoiLienHe != value))
				{
					this.OnDienThoaiNguoiLienHeChanging(value);
					this.SendPropertyChanging();
					this._DienThoaiNguoiLienHe = value;
					this.SendPropertyChanged("DienThoaiNguoiLienHe");
					this.OnDienThoaiNguoiLienHeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CompanyID", DbType="Int")]
		public System.Nullable<int> CompanyID
		{
			get
			{
				return this._CompanyID;
			}
			set
			{
				if ((this._CompanyID != value))
				{
					this.OnCompanyIDChanging(value);
					this.SendPropertyChanging();
					this._CompanyID = value;
					this.SendPropertyChanged("CompanyID");
					this.OnCompanyIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CompanyName", DbType="NVarChar(50)")]
		public string CompanyName
		{
			get
			{
				return this._CompanyName;
			}
			set
			{
				if ((this._CompanyName != value))
				{
					this.OnCompanyNameChanging(value);
					this.SendPropertyChanging();
					this._CompanyName = value;
					this.SendPropertyChanged("CompanyName");
					this.OnCompanyNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DepartmentID", DbType="Int")]
		public System.Nullable<int> DepartmentID
		{
			get
			{
				return this._DepartmentID;
			}
			set
			{
				if ((this._DepartmentID != value))
				{
					this.OnDepartmentIDChanging(value);
					this.SendPropertyChanging();
					this._DepartmentID = value;
					this.SendPropertyChanged("DepartmentID");
					this.OnDepartmentIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DepartmentName", DbType="NVarChar(50)")]
		public string DepartmentName
		{
			get
			{
				return this._DepartmentName;
			}
			set
			{
				if ((this._DepartmentName != value))
				{
					this.OnDepartmentNameChanging(value);
					this.SendPropertyChanging();
					this._DepartmentName = value;
					this.SendPropertyChanged("DepartmentName");
					this.OnDepartmentNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MucDichCongViec", DbType="NVarChar(MAX)")]
		public string MucDichCongViec
		{
			get
			{
				return this._MucDichCongViec;
			}
			set
			{
				if ((this._MucDichCongViec != value))
				{
					this.OnMucDichCongViecChanging(value);
					this.SendPropertyChanging();
					this._MucDichCongViec = value;
					this.SendPropertyChanged("MucDichCongViec");
					this.OnMucDichCongViecChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AnhCMNDPath", DbType="NVarChar(250)")]
		public string AnhCMNDPath
		{
			get
			{
				return this._AnhCMNDPath;
			}
			set
			{
				if ((this._AnhCMNDPath != value))
				{
					this.OnAnhCMNDPathChanging(value);
					this.SendPropertyChanging();
					this._AnhCMNDPath = value;
					this.SendPropertyChanged("AnhCMNDPath");
					this.OnAnhCMNDPathChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AnhKhuonMatPath", DbType="NVarChar(250)")]
		public string AnhKhuonMatPath
		{
			get
			{
				return this._AnhKhuonMatPath;
			}
			set
			{
				if ((this._AnhKhuonMatPath != value))
				{
					this.OnAnhKhuonMatPathChanging(value);
					this.SendPropertyChanging();
					this._AnhKhuonMatPath = value;
					this.SendPropertyChanged("AnhKhuonMatPath");
					this.OnAnhKhuonMatPathChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GhiChu", DbType="NVarChar(500)")]
		public string GhiChu
		{
			get
			{
				return this._GhiChu;
			}
			set
			{
				if ((this._GhiChu != value))
				{
					this.OnGhiChuChanging(value);
					this.SendPropertyChanging();
					this._GhiChu = value;
					this.SendPropertyChanged("GhiChu");
					this.OnGhiChuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NguoiDangKyVao", DbType="NVarChar(50)")]
		public string NguoiDangKyVao
		{
			get
			{
				return this._NguoiDangKyVao;
			}
			set
			{
				if ((this._NguoiDangKyVao != value))
				{
					this.OnNguoiDangKyVaoChanging(value);
					this.SendPropertyChanging();
					this._NguoiDangKyVao = value;
					this.SendPropertyChanged("NguoiDangKyVao");
					this.OnNguoiDangKyVaoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NguoiXacNhanVao", DbType="NVarChar(50)")]
		public string NguoiXacNhanVao
		{
			get
			{
				return this._NguoiXacNhanVao;
			}
			set
			{
				if ((this._NguoiXacNhanVao != value))
				{
					this.OnNguoiXacNhanVaoChanging(value);
					this.SendPropertyChanging();
					this._NguoiXacNhanVao = value;
					this.SendPropertyChanged("NguoiXacNhanVao");
					this.OnNguoiXacNhanVaoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TrangThai", DbType="Int")]
		public System.Nullable<int> TrangThai
		{
			get
			{
				return this._TrangThai;
			}
			set
			{
				if ((this._TrangThai != value))
				{
					this.OnTrangThaiChanging(value);
					this.SendPropertyChanging();
					this._TrangThai = value;
					this.SendPropertyChanged("TrangThai");
					this.OnTrangThaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayGioRa", DbType="DateTime")]
		public System.Nullable<System.DateTime> NgayGioRa
		{
			get
			{
				return this._NgayGioRa;
			}
			set
			{
				if ((this._NgayGioRa != value))
				{
					this.OnNgayGioRaChanging(value);
					this.SendPropertyChanging();
					this._NgayGioRa = value;
					this.SendPropertyChanged("NgayGioRa");
					this.OnNgayGioRaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KetQuaKiemTraRa", DbType="NVarChar(500)")]
		public string KetQuaKiemTraRa
		{
			get
			{
				return this._KetQuaKiemTraRa;
			}
			set
			{
				if ((this._KetQuaKiemTraRa != value))
				{
					this.OnKetQuaKiemTraRaChanging(value);
					this.SendPropertyChanging();
					this._KetQuaKiemTraRa = value;
					this.SendPropertyChanged("KetQuaKiemTraRa");
					this.OnKetQuaKiemTraRaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NguoiKiemTraRa", DbType="NVarChar(50)")]
		public string NguoiKiemTraRa
		{
			get
			{
				return this._NguoiKiemTraRa;
			}
			set
			{
				if ((this._NguoiKiemTraRa != value))
				{
					this.OnNguoiKiemTraRaChanging(value);
					this.SendPropertyChanging();
					this._NguoiKiemTraRa = value;
					this.SendPropertyChanged("NguoiKiemTraRa");
					this.OnNguoiKiemTraRaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsSync", DbType="Bit")]
		public System.Nullable<bool> IsSync
		{
			get
			{
				return this._IsSync;
			}
			set
			{
				if ((this._IsSync != value))
				{
					this.OnIsSyncChanging(value);
					this.SendPropertyChanging();
					this._IsSync = value;
					this.SendPropertyChanged("IsSync");
					this.OnIsSyncChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SyncID", DbType="NVarChar(50)")]
		public string SyncID
		{
			get
			{
				return this._SyncID;
			}
			set
			{
				if ((this._SyncID != value))
				{
					this.OnSyncIDChanging(value);
					this.SendPropertyChanging();
					this._SyncID = value;
					this.SendPropertyChanged("SyncID");
					this.OnSyncIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Floor", DbType="Int")]
		public System.Nullable<int> Floor
		{
			get
			{
				return this._Floor;
			}
			set
			{
				if ((this._Floor != value))
				{
					this.OnFloorChanging(value);
					this.SendPropertyChanging();
					this._Floor = value;
					this.SendPropertyChanged("Floor");
					this.OnFloorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayGioVaoThuc", DbType="DateTime")]
		public System.Nullable<System.DateTime> NgayGioVaoThuc
		{
			get
			{
				return this._NgayGioVaoThuc;
			}
			set
			{
				if ((this._NgayGioVaoThuc != value))
				{
					this.OnNgayGioVaoThucChanging(value);
					this.SendPropertyChanging();
					this._NgayGioVaoThuc = value;
					this.SendPropertyChanged("NgayGioVaoThuc");
					this.OnNgayGioVaoThucChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.LocationConfig")]
	public partial class LocationConfig : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private System.Nullable<int> _Floor;
		
		private System.Nullable<int> _TotalSpace;
		
		private System.Nullable<int> _ThresholdPoint;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnFloorChanging(System.Nullable<int> value);
    partial void OnFloorChanged();
    partial void OnTotalSpaceChanging(System.Nullable<int> value);
    partial void OnTotalSpaceChanged();
    partial void OnThresholdPointChanging(System.Nullable<int> value);
    partial void OnThresholdPointChanged();
    #endregion
		
		public LocationConfig()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Floor", DbType="Int")]
		public System.Nullable<int> Floor
		{
			get
			{
				return this._Floor;
			}
			set
			{
				if ((this._Floor != value))
				{
					this.OnFloorChanging(value);
					this.SendPropertyChanging();
					this._Floor = value;
					this.SendPropertyChanged("Floor");
					this.OnFloorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TotalSpace", DbType="Int")]
		public System.Nullable<int> TotalSpace
		{
			get
			{
				return this._TotalSpace;
			}
			set
			{
				if ((this._TotalSpace != value))
				{
					this.OnTotalSpaceChanging(value);
					this.SendPropertyChanging();
					this._TotalSpace = value;
					this.SendPropertyChanged("TotalSpace");
					this.OnTotalSpaceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ThresholdPoint", DbType="Int")]
		public System.Nullable<int> ThresholdPoint
		{
			get
			{
				return this._ThresholdPoint;
			}
			set
			{
				if ((this._ThresholdPoint != value))
				{
					this.OnThresholdPointChanging(value);
					this.SendPropertyChanging();
					this._ThresholdPoint = value;
					this.SendPropertyChanged("ThresholdPoint");
					this.OnThresholdPointChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblTicketStatus")]
	public partial class tblTicketStatus : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private System.Guid _TicketUID;
		
		private System.Nullable<System.DateTime> _TicketCreatedAt;
		
		private string _ActionCode;
		
		private string _ActionValue;
		
		private System.DateTime _ActionDateTime;
		
		private string _BienSoXe;
		
		private System.Nullable<int> _ActionStatus;
		
		private string _ActionMessage;
		
		private string _QrScan;
		
		private System.Nullable<int> _TicketType;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnTicketUIDChanging(System.Guid value);
    partial void OnTicketUIDChanged();
    partial void OnTicketCreatedAtChanging(System.Nullable<System.DateTime> value);
    partial void OnTicketCreatedAtChanged();
    partial void OnActionCodeChanging(string value);
    partial void OnActionCodeChanged();
    partial void OnActionValueChanging(string value);
    partial void OnActionValueChanged();
    partial void OnActionDateTimeChanging(System.DateTime value);
    partial void OnActionDateTimeChanged();
    partial void OnBienSoXeChanging(string value);
    partial void OnBienSoXeChanged();
    partial void OnActionStatusChanging(System.Nullable<int> value);
    partial void OnActionStatusChanged();
    partial void OnActionMessageChanging(string value);
    partial void OnActionMessageChanged();
    partial void OnQrScanChanging(string value);
    partial void OnQrScanChanged();
    partial void OnTicketTypeChanging(System.Nullable<int> value);
    partial void OnTicketTypeChanged();
    #endregion
		
		public tblTicketStatus()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TicketUID", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid TicketUID
		{
			get
			{
				return this._TicketUID;
			}
			set
			{
				if ((this._TicketUID != value))
				{
					this.OnTicketUIDChanging(value);
					this.SendPropertyChanging();
					this._TicketUID = value;
					this.SendPropertyChanged("TicketUID");
					this.OnTicketUIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TicketCreatedAt", DbType="DateTime2")]
		public System.Nullable<System.DateTime> TicketCreatedAt
		{
			get
			{
				return this._TicketCreatedAt;
			}
			set
			{
				if ((this._TicketCreatedAt != value))
				{
					this.OnTicketCreatedAtChanging(value);
					this.SendPropertyChanging();
					this._TicketCreatedAt = value;
					this.SendPropertyChanged("TicketCreatedAt");
					this.OnTicketCreatedAtChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ActionCode", DbType="NVarChar(50)")]
		public string ActionCode
		{
			get
			{
				return this._ActionCode;
			}
			set
			{
				if ((this._ActionCode != value))
				{
					this.OnActionCodeChanging(value);
					this.SendPropertyChanging();
					this._ActionCode = value;
					this.SendPropertyChanged("ActionCode");
					this.OnActionCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ActionValue", DbType="NVarChar(50)")]
		public string ActionValue
		{
			get
			{
				return this._ActionValue;
			}
			set
			{
				if ((this._ActionValue != value))
				{
					this.OnActionValueChanging(value);
					this.SendPropertyChanging();
					this._ActionValue = value;
					this.SendPropertyChanged("ActionValue");
					this.OnActionValueChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ActionDateTime", DbType="DateTime2 NOT NULL")]
		public System.DateTime ActionDateTime
		{
			get
			{
				return this._ActionDateTime;
			}
			set
			{
				if ((this._ActionDateTime != value))
				{
					this.OnActionDateTimeChanging(value);
					this.SendPropertyChanging();
					this._ActionDateTime = value;
					this.SendPropertyChanged("ActionDateTime");
					this.OnActionDateTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BienSoXe", DbType="VarChar(50)")]
		public string BienSoXe
		{
			get
			{
				return this._BienSoXe;
			}
			set
			{
				if ((this._BienSoXe != value))
				{
					this.OnBienSoXeChanging(value);
					this.SendPropertyChanging();
					this._BienSoXe = value;
					this.SendPropertyChanged("BienSoXe");
					this.OnBienSoXeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ActionStatus", DbType="Int")]
		public System.Nullable<int> ActionStatus
		{
			get
			{
				return this._ActionStatus;
			}
			set
			{
				if ((this._ActionStatus != value))
				{
					this.OnActionStatusChanging(value);
					this.SendPropertyChanging();
					this._ActionStatus = value;
					this.SendPropertyChanged("ActionStatus");
					this.OnActionStatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ActionMessage", DbType="NVarChar(255)")]
		public string ActionMessage
		{
			get
			{
				return this._ActionMessage;
			}
			set
			{
				if ((this._ActionMessage != value))
				{
					this.OnActionMessageChanging(value);
					this.SendPropertyChanging();
					this._ActionMessage = value;
					this.SendPropertyChanged("ActionMessage");
					this.OnActionMessageChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_QrScan", DbType="NVarChar(255)")]
		public string QrScan
		{
			get
			{
				return this._QrScan;
			}
			set
			{
				if ((this._QrScan != value))
				{
					this.OnQrScanChanging(value);
					this.SendPropertyChanging();
					this._QrScan = value;
					this.SendPropertyChanged("QrScan");
					this.OnQrScanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TicketType", DbType="Int")]
		public System.Nullable<int> TicketType
		{
			get
			{
				return this._TicketType;
			}
			set
			{
				if ((this._TicketType != value))
				{
					this.OnTicketTypeChanging(value);
					this.SendPropertyChanging();
					this._TicketType = value;
					this.SendPropertyChanged("TicketType");
					this.OnTicketTypeChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CallTruck")]
	public partial class CallTruck : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _BSX;
		
		private string _Location;
		
		private System.Nullable<int> _Floor;
		
		private System.Nullable<System.DateTime> _Created;
		
		private string _Note;
		
		private string _Remark;
		
		private System.Nullable<int> _SortValue;
		
		private string _VCT;
		
		private System.Nullable<int> _SpaceEmptyFloor1;
		
		private System.Nullable<int> _SpaceEmptyFloor2;
		
		private string _Dock;
		
		private System.Nullable<System.DateTime> _TimeCalled;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnBSXChanging(string value);
    partial void OnBSXChanged();
    partial void OnLocationChanging(string value);
    partial void OnLocationChanged();
    partial void OnFloorChanging(System.Nullable<int> value);
    partial void OnFloorChanged();
    partial void OnCreatedChanging(System.Nullable<System.DateTime> value);
    partial void OnCreatedChanged();
    partial void OnNoteChanging(string value);
    partial void OnNoteChanged();
    partial void OnRemarkChanging(string value);
    partial void OnRemarkChanged();
    partial void OnSortValueChanging(System.Nullable<int> value);
    partial void OnSortValueChanged();
    partial void OnVCTChanging(string value);
    partial void OnVCTChanged();
    partial void OnSpaceEmptyFloor1Changing(System.Nullable<int> value);
    partial void OnSpaceEmptyFloor1Changed();
    partial void OnSpaceEmptyFloor2Changing(System.Nullable<int> value);
    partial void OnSpaceEmptyFloor2Changed();
    partial void OnDockChanging(string value);
    partial void OnDockChanged();
    partial void OnTimeCalledChanging(System.Nullable<System.DateTime> value);
    partial void OnTimeCalledChanged();
    #endregion
		
		public CallTruck()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BSX", DbType="VarChar(50)")]
		public string BSX
		{
			get
			{
				return this._BSX;
			}
			set
			{
				if ((this._BSX != value))
				{
					this.OnBSXChanging(value);
					this.SendPropertyChanging();
					this._BSX = value;
					this.SendPropertyChanged("BSX");
					this.OnBSXChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Location", DbType="VarChar(50)")]
		public string Location
		{
			get
			{
				return this._Location;
			}
			set
			{
				if ((this._Location != value))
				{
					this.OnLocationChanging(value);
					this.SendPropertyChanging();
					this._Location = value;
					this.SendPropertyChanged("Location");
					this.OnLocationChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Floor", DbType="Int")]
		public System.Nullable<int> Floor
		{
			get
			{
				return this._Floor;
			}
			set
			{
				if ((this._Floor != value))
				{
					this.OnFloorChanging(value);
					this.SendPropertyChanging();
					this._Floor = value;
					this.SendPropertyChanged("Floor");
					this.OnFloorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Created", DbType="DateTime")]
		public System.Nullable<System.DateTime> Created
		{
			get
			{
				return this._Created;
			}
			set
			{
				if ((this._Created != value))
				{
					this.OnCreatedChanging(value);
					this.SendPropertyChanging();
					this._Created = value;
					this.SendPropertyChanged("Created");
					this.OnCreatedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Note", DbType="NVarChar(50)")]
		public string Note
		{
			get
			{
				return this._Note;
			}
			set
			{
				if ((this._Note != value))
				{
					this.OnNoteChanging(value);
					this.SendPropertyChanging();
					this._Note = value;
					this.SendPropertyChanged("Note");
					this.OnNoteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Remark", DbType="VarChar(50)")]
		public string Remark
		{
			get
			{
				return this._Remark;
			}
			set
			{
				if ((this._Remark != value))
				{
					this.OnRemarkChanging(value);
					this.SendPropertyChanging();
					this._Remark = value;
					this.SendPropertyChanged("Remark");
					this.OnRemarkChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SortValue", DbType="Int")]
		public System.Nullable<int> SortValue
		{
			get
			{
				return this._SortValue;
			}
			set
			{
				if ((this._SortValue != value))
				{
					this.OnSortValueChanging(value);
					this.SendPropertyChanging();
					this._SortValue = value;
					this.SendPropertyChanged("SortValue");
					this.OnSortValueChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VCT", DbType="VarChar(50)")]
		public string VCT
		{
			get
			{
				return this._VCT;
			}
			set
			{
				if ((this._VCT != value))
				{
					this.OnVCTChanging(value);
					this.SendPropertyChanging();
					this._VCT = value;
					this.SendPropertyChanged("VCT");
					this.OnVCTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SpaceEmptyFloor1", DbType="Int")]
		public System.Nullable<int> SpaceEmptyFloor1
		{
			get
			{
				return this._SpaceEmptyFloor1;
			}
			set
			{
				if ((this._SpaceEmptyFloor1 != value))
				{
					this.OnSpaceEmptyFloor1Changing(value);
					this.SendPropertyChanging();
					this._SpaceEmptyFloor1 = value;
					this.SendPropertyChanged("SpaceEmptyFloor1");
					this.OnSpaceEmptyFloor1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SpaceEmptyFloor2", DbType="Int")]
		public System.Nullable<int> SpaceEmptyFloor2
		{
			get
			{
				return this._SpaceEmptyFloor2;
			}
			set
			{
				if ((this._SpaceEmptyFloor2 != value))
				{
					this.OnSpaceEmptyFloor2Changing(value);
					this.SendPropertyChanging();
					this._SpaceEmptyFloor2 = value;
					this.SendPropertyChanged("SpaceEmptyFloor2");
					this.OnSpaceEmptyFloor2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Dock", DbType="NVarChar(50)")]
		public string Dock
		{
			get
			{
				return this._Dock;
			}
			set
			{
				if ((this._Dock != value))
				{
					this.OnDockChanging(value);
					this.SendPropertyChanging();
					this._Dock = value;
					this.SendPropertyChanged("Dock");
					this.OnDockChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TimeCalled", DbType="DateTime")]
		public System.Nullable<System.DateTime> TimeCalled
		{
			get
			{
				return this._TimeCalled;
			}
			set
			{
				if ((this._TimeCalled != value))
				{
					this.OnTimeCalledChanging(value);
					this.SendPropertyChanging();
					this._TimeCalled = value;
					this.SendPropertyChanged("TimeCalled");
					this.OnTimeCalledChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblDangKyGoiXe")]
	public partial class tblDangKyGoiXe : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _BienSoXe;
		
		private string _TrongTai;
		
		private string _LoHang;
		
		private System.Nullable<int> _LoaiHang;
		
		private string _TenLaiXe;
		
		private string _SoCMND;
		
		private System.Nullable<int> _ViTri;
		
		private System.Nullable<int> _TrangThai;
		
		private System.Nullable<System.DateTime> _ThoiGianDangKy;
		
		private System.Nullable<System.DateTime> _ThoiGianVao;
		
		private System.Nullable<System.DateTime> _ThoiGianRa;
		
		private string _GhiChu;
		
		private string _DienThoai;
		
		private System.Nullable<bool> _QueryStatus;
		
		private System.Nullable<int> _CallTruck;
		
		private string _Remark;
		
		private System.Nullable<int> _SortValue;
		
		private string _UserName;
		
		private string _Note;
		
		private System.Nullable<System.DateTime> _GioGoi;
		
		private System.Nullable<System.Guid> _SynID;
		
		private System.Nullable<int> _TruckStatus;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnBienSoXeChanging(string value);
    partial void OnBienSoXeChanged();
    partial void OnTrongTaiChanging(string value);
    partial void OnTrongTaiChanged();
    partial void OnLoHangChanging(string value);
    partial void OnLoHangChanged();
    partial void OnLoaiHangChanging(System.Nullable<int> value);
    partial void OnLoaiHangChanged();
    partial void OnTenLaiXeChanging(string value);
    partial void OnTenLaiXeChanged();
    partial void OnSoCMNDChanging(string value);
    partial void OnSoCMNDChanged();
    partial void OnViTriChanging(System.Nullable<int> value);
    partial void OnViTriChanged();
    partial void OnTrangThaiChanging(System.Nullable<int> value);
    partial void OnTrangThaiChanged();
    partial void OnThoiGianDangKyChanging(System.Nullable<System.DateTime> value);
    partial void OnThoiGianDangKyChanged();
    partial void OnThoiGianVaoChanging(System.Nullable<System.DateTime> value);
    partial void OnThoiGianVaoChanged();
    partial void OnThoiGianRaChanging(System.Nullable<System.DateTime> value);
    partial void OnThoiGianRaChanged();
    partial void OnGhiChuChanging(string value);
    partial void OnGhiChuChanged();
    partial void OnDienThoaiChanging(string value);
    partial void OnDienThoaiChanged();
    partial void OnQueryStatusChanging(System.Nullable<bool> value);
    partial void OnQueryStatusChanged();
    partial void OnCallTruckChanging(System.Nullable<int> value);
    partial void OnCallTruckChanged();
    partial void OnRemarkChanging(string value);
    partial void OnRemarkChanged();
    partial void OnSortValueChanging(System.Nullable<int> value);
    partial void OnSortValueChanged();
    partial void OnUserNameChanging(string value);
    partial void OnUserNameChanged();
    partial void OnNoteChanging(string value);
    partial void OnNoteChanged();
    partial void OnGioGoiChanging(System.Nullable<System.DateTime> value);
    partial void OnGioGoiChanged();
    partial void OnSynIDChanging(System.Nullable<System.Guid> value);
    partial void OnSynIDChanged();
    partial void OnTruckStatusChanging(System.Nullable<int> value);
    partial void OnTruckStatusChanged();
    #endregion
		
		public tblDangKyGoiXe()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BienSoXe", DbType="NVarChar(50)")]
		public string BienSoXe
		{
			get
			{
				return this._BienSoXe;
			}
			set
			{
				if ((this._BienSoXe != value))
				{
					this.OnBienSoXeChanging(value);
					this.SendPropertyChanging();
					this._BienSoXe = value;
					this.SendPropertyChanged("BienSoXe");
					this.OnBienSoXeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TrongTai", DbType="NVarChar(100)")]
		public string TrongTai
		{
			get
			{
				return this._TrongTai;
			}
			set
			{
				if ((this._TrongTai != value))
				{
					this.OnTrongTaiChanging(value);
					this.SendPropertyChanging();
					this._TrongTai = value;
					this.SendPropertyChanged("TrongTai");
					this.OnTrongTaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LoHang", DbType="NVarChar(100)")]
		public string LoHang
		{
			get
			{
				return this._LoHang;
			}
			set
			{
				if ((this._LoHang != value))
				{
					this.OnLoHangChanging(value);
					this.SendPropertyChanging();
					this._LoHang = value;
					this.SendPropertyChanged("LoHang");
					this.OnLoHangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LoaiHang", DbType="Int")]
		public System.Nullable<int> LoaiHang
		{
			get
			{
				return this._LoaiHang;
			}
			set
			{
				if ((this._LoaiHang != value))
				{
					this.OnLoaiHangChanging(value);
					this.SendPropertyChanging();
					this._LoaiHang = value;
					this.SendPropertyChanged("LoaiHang");
					this.OnLoaiHangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenLaiXe", DbType="NVarChar(100)")]
		public string TenLaiXe
		{
			get
			{
				return this._TenLaiXe;
			}
			set
			{
				if ((this._TenLaiXe != value))
				{
					this.OnTenLaiXeChanging(value);
					this.SendPropertyChanging();
					this._TenLaiXe = value;
					this.SendPropertyChanged("TenLaiXe");
					this.OnTenLaiXeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoCMND", DbType="VarChar(50)")]
		public string SoCMND
		{
			get
			{
				return this._SoCMND;
			}
			set
			{
				if ((this._SoCMND != value))
				{
					this.OnSoCMNDChanging(value);
					this.SendPropertyChanging();
					this._SoCMND = value;
					this.SendPropertyChanged("SoCMND");
					this.OnSoCMNDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ViTri", DbType="Int")]
		public System.Nullable<int> ViTri
		{
			get
			{
				return this._ViTri;
			}
			set
			{
				if ((this._ViTri != value))
				{
					this.OnViTriChanging(value);
					this.SendPropertyChanging();
					this._ViTri = value;
					this.SendPropertyChanged("ViTri");
					this.OnViTriChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TrangThai", DbType="Int")]
		public System.Nullable<int> TrangThai
		{
			get
			{
				return this._TrangThai;
			}
			set
			{
				if ((this._TrangThai != value))
				{
					this.OnTrangThaiChanging(value);
					this.SendPropertyChanging();
					this._TrangThai = value;
					this.SendPropertyChanged("TrangThai");
					this.OnTrangThaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ThoiGianDangKy", DbType="DateTime")]
		public System.Nullable<System.DateTime> ThoiGianDangKy
		{
			get
			{
				return this._ThoiGianDangKy;
			}
			set
			{
				if ((this._ThoiGianDangKy != value))
				{
					this.OnThoiGianDangKyChanging(value);
					this.SendPropertyChanging();
					this._ThoiGianDangKy = value;
					this.SendPropertyChanged("ThoiGianDangKy");
					this.OnThoiGianDangKyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ThoiGianVao", DbType="DateTime")]
		public System.Nullable<System.DateTime> ThoiGianVao
		{
			get
			{
				return this._ThoiGianVao;
			}
			set
			{
				if ((this._ThoiGianVao != value))
				{
					this.OnThoiGianVaoChanging(value);
					this.SendPropertyChanging();
					this._ThoiGianVao = value;
					this.SendPropertyChanged("ThoiGianVao");
					this.OnThoiGianVaoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ThoiGianRa", DbType="DateTime")]
		public System.Nullable<System.DateTime> ThoiGianRa
		{
			get
			{
				return this._ThoiGianRa;
			}
			set
			{
				if ((this._ThoiGianRa != value))
				{
					this.OnThoiGianRaChanging(value);
					this.SendPropertyChanging();
					this._ThoiGianRa = value;
					this.SendPropertyChanged("ThoiGianRa");
					this.OnThoiGianRaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GhiChu", DbType="NVarChar(250)")]
		public string GhiChu
		{
			get
			{
				return this._GhiChu;
			}
			set
			{
				if ((this._GhiChu != value))
				{
					this.OnGhiChuChanging(value);
					this.SendPropertyChanging();
					this._GhiChu = value;
					this.SendPropertyChanged("GhiChu");
					this.OnGhiChuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DienThoai", DbType="NVarChar(100)")]
		public string DienThoai
		{
			get
			{
				return this._DienThoai;
			}
			set
			{
				if ((this._DienThoai != value))
				{
					this.OnDienThoaiChanging(value);
					this.SendPropertyChanging();
					this._DienThoai = value;
					this.SendPropertyChanged("DienThoai");
					this.OnDienThoaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_QueryStatus", DbType="Bit")]
		public System.Nullable<bool> QueryStatus
		{
			get
			{
				return this._QueryStatus;
			}
			set
			{
				if ((this._QueryStatus != value))
				{
					this.OnQueryStatusChanging(value);
					this.SendPropertyChanging();
					this._QueryStatus = value;
					this.SendPropertyChanged("QueryStatus");
					this.OnQueryStatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CallTruck", DbType="Int")]
		public System.Nullable<int> CallTruck
		{
			get
			{
				return this._CallTruck;
			}
			set
			{
				if ((this._CallTruck != value))
				{
					this.OnCallTruckChanging(value);
					this.SendPropertyChanging();
					this._CallTruck = value;
					this.SendPropertyChanged("CallTruck");
					this.OnCallTruckChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Remark", DbType="VarChar(50)")]
		public string Remark
		{
			get
			{
				return this._Remark;
			}
			set
			{
				if ((this._Remark != value))
				{
					this.OnRemarkChanging(value);
					this.SendPropertyChanging();
					this._Remark = value;
					this.SendPropertyChanged("Remark");
					this.OnRemarkChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SortValue", DbType="Int")]
		public System.Nullable<int> SortValue
		{
			get
			{
				return this._SortValue;
			}
			set
			{
				if ((this._SortValue != value))
				{
					this.OnSortValueChanging(value);
					this.SendPropertyChanging();
					this._SortValue = value;
					this.SendPropertyChanged("SortValue");
					this.OnSortValueChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserName", DbType="NVarChar(50)")]
		public string UserName
		{
			get
			{
				return this._UserName;
			}
			set
			{
				if ((this._UserName != value))
				{
					this.OnUserNameChanging(value);
					this.SendPropertyChanging();
					this._UserName = value;
					this.SendPropertyChanged("UserName");
					this.OnUserNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Note", DbType="NVarChar(200)")]
		public string Note
		{
			get
			{
				return this._Note;
			}
			set
			{
				if ((this._Note != value))
				{
					this.OnNoteChanging(value);
					this.SendPropertyChanging();
					this._Note = value;
					this.SendPropertyChanged("Note");
					this.OnNoteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GioGoi", DbType="DateTime")]
		public System.Nullable<System.DateTime> GioGoi
		{
			get
			{
				return this._GioGoi;
			}
			set
			{
				if ((this._GioGoi != value))
				{
					this.OnGioGoiChanging(value);
					this.SendPropertyChanging();
					this._GioGoi = value;
					this.SendPropertyChanged("GioGoi");
					this.OnGioGoiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SynID", DbType="UniqueIdentifier")]
		public System.Nullable<System.Guid> SynID
		{
			get
			{
				return this._SynID;
			}
			set
			{
				if ((this._SynID != value))
				{
					this.OnSynIDChanging(value);
					this.SendPropertyChanging();
					this._SynID = value;
					this.SendPropertyChanged("SynID");
					this.OnSynIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TruckStatus", DbType="Int")]
		public System.Nullable<int> TruckStatus
		{
			get
			{
				return this._TruckStatus;
			}
			set
			{
				if ((this._TruckStatus != value))
				{
					this.OnTruckStatusChanging(value);
					this.SendPropertyChanging();
					this._TruckStatus = value;
					this.SendPropertyChanged("TruckStatus");
					this.OnTruckStatusChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
