//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TASK.DATA.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=.;Initial Catalog=ALSC_SyncData;User ID=sa")]
        public string ALSC_SyncDataConnectionString {
            get {
                return ((string)(this["ALSC_SyncDataConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=.;Initial Catalog=ALSC_SyncData;User ID=sa;Password=123456")]
        public string ALSC_SyncDataConnectionString1 {
            get {
                return ((string)(this["ALSC_SyncDataConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=.;Initial Catalog=ALSC_SyncData;Integrated Security=True")]
        public string ALSC_SyncDataConnectionString2 {
            get {
                return ((string)(this["ALSC_SyncDataConnectionString2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=10.10.1.10;Initial Catalog=ALSC_SyncData;User ID=sa;Password=abc@123@" +
            "456@789")]
        public string ALSC_SyncDataConnectionString3 {
            get {
                return ((string)(this["ALSC_SyncDataConnectionString3"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=10.10.1.10;Initial Catalog=ALSC_FLIGHTCONTROL;User ID=sa;Password=abc" +
            "@123@456@789")]
        public string ALSC_FLIGHTCONTROLConnectionString {
            get {
                return ((string)(this["ALSC_FLIGHTCONTROLConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=10.10.1.10;Initial Catalog=DBSPM.ALSNOIBAI;Persist Security Info=True" +
            ";User ID=sa;Password=abc@123@456@789")]
        public string DBSPM_ALSNOIBAIConnectionString {
            get {
                return ((string)(this["DBSPM_ALSNOIBAIConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=10.10.1.10;Initial Catalog=DBSPM.ALSNOIBAI;User ID=sa;Password=abc@12" +
            "3@456@789")]
        public string DBSPM_ALSNOIBAIConnectionString1 {
            get {
                return ((string)(this["DBSPM_ALSNOIBAIConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=10.10.1.10;Initial Catalog=QMSTickets;User ID=sa;Password=abc@123@456" +
            "@789")]
        public string QMSTicketsConnectionString {
            get {
                return ((string)(this["QMSTicketsConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=10.10.1.10;Initial Catalog=ConnectALS;User ID=sa;Password=abc@123@456" +
            "@789")]
        public string ConnectALSConnectionString {
            get {
                return ((string)(this["ConnectALSConnectionString"]));
            }
        }
    }
}
